//
// Copyright 2024 hopeio. All rights reserved.
// Licensed under the MIT License that can be found in the LICENSE file.
// @Created by jyb

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.32.0
// source: hopeio/model/basic.proto

package model

import (
	deletedAt "github.com/hopeio/protobuf/time/deletedAt"
	timestamp "github.com/hopeio/protobuf/time/timestamp"
	_ "github.com/hopeio/protobuf/utils/patch"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ModelTimeStr struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CreatedAt     string                 `protobuf:"bytes,1,opt,name=createdAt,proto3" json:"createdAt,omitempty" gorm:"type:timestamptz(6);default:now();index"`
	UpdatedAt     string                 `protobuf:"bytes,2,opt,name=updatedAt,proto3" json:"updatedAt,omitempty" gorm:"type:timestamptz(6)"`
	DeletedAt     string                 `protobuf:"bytes,3,opt,name=deletedAt,proto3" json:"deletedAt,omitempty" gorm:"<-:false;type:timestamptz(6);index"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ModelTimeStr) Reset() {
	*x = ModelTimeStr{}
	mi := &file_hopeio_model_basic_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ModelTimeStr) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ModelTimeStr) ProtoMessage() {}

func (x *ModelTimeStr) ProtoReflect() protoreflect.Message {
	mi := &file_hopeio_model_basic_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ModelTimeStr.ProtoReflect.Descriptor instead.
func (*ModelTimeStr) Descriptor() ([]byte, []int) {
	return file_hopeio_model_basic_proto_rawDescGZIP(), []int{0}
}

func (x *ModelTimeStr) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *ModelTimeStr) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

func (x *ModelTimeStr) GetDeletedAt() string {
	if x != nil {
		return x.DeletedAt
	}
	return ""
}

type ModelTime struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CreatedAt     *timestamp.Timestamp   `protobuf:"bytes,1,opt,name=createdAt,proto3" json:"createdAt,omitempty" gorm:"type:timestamptz(6);default:now();index"`
	UpdatedAt     *timestamp.Timestamp   `protobuf:"bytes,2,opt,name=updatedAt,proto3" json:"updatedAt,omitempty" gorm:"type:timestamptz(6)"`
	DeletedAt     *deletedAt.DeletedAt   `protobuf:"bytes,3,opt,name=deletedAt,proto3" json:"deletedAt,omitempty" gorm:"<-:false;type:timestamptz(6);index"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ModelTime) Reset() {
	*x = ModelTime{}
	mi := &file_hopeio_model_basic_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ModelTime) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ModelTime) ProtoMessage() {}

func (x *ModelTime) ProtoReflect() protoreflect.Message {
	mi := &file_hopeio_model_basic_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ModelTime.ProtoReflect.Descriptor instead.
func (*ModelTime) Descriptor() ([]byte, []int) {
	return file_hopeio_model_basic_proto_rawDescGZIP(), []int{1}
}

func (x *ModelTime) GetCreatedAt() *timestamp.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *ModelTime) GetUpdatedAt() *timestamp.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *ModelTime) GetDeletedAt() *deletedAt.DeletedAt {
	if x != nil {
		return x.DeletedAt
	}
	return nil
}

type ModelTimeInt struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CreatedAt     int64                  `protobuf:"varint,1,opt,name=createdAt,proto3" json:"createdAt,omitempty" gorm:"type:timestamptz(6);default:now();index"`
	UpdatedAt     int64                  `protobuf:"varint,2,opt,name=updatedAt,proto3" json:"updatedAt,omitempty" gorm:"type:timestamptz(6)"`
	DeletedAt     int64                  `protobuf:"varint,3,opt,name=deletedAt,proto3" json:"deletedAt,omitempty" gorm:"<-:false;type:timestamptz(6);index"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ModelTimeInt) Reset() {
	*x = ModelTimeInt{}
	mi := &file_hopeio_model_basic_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ModelTimeInt) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ModelTimeInt) ProtoMessage() {}

func (x *ModelTimeInt) ProtoReflect() protoreflect.Message {
	mi := &file_hopeio_model_basic_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ModelTimeInt.ProtoReflect.Descriptor instead.
func (*ModelTimeInt) Descriptor() ([]byte, []int) {
	return file_hopeio_model_basic_proto_rawDescGZIP(), []int{2}
}

func (x *ModelTimeInt) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *ModelTimeInt) GetUpdatedAt() int64 {
	if x != nil {
		return x.UpdatedAt
	}
	return 0
}

func (x *ModelTimeInt) GetDeletedAt() int64 {
	if x != nil {
		return x.DeletedAt
	}
	return 0
}

type Model struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty" gorm:"primaryKey"`
	CreatedAt     *timestamp.Timestamp   `protobuf:"bytes,2,opt,name=createdAt,proto3" json:"createdAt,omitempty" gorm:"type:timestamptz(6);default:now()"`
	UpdatedAt     *timestamp.Timestamp   `protobuf:"bytes,3,opt,name=updatedAt,proto3" json:"updatedAt,omitempty" gorm:"type:timestamptz(6)"`
	DeletedAt     *deletedAt.DeletedAt   `protobuf:"bytes,4,opt,name=deletedAt,proto3" json:"deletedAt,omitempty" gorm:"<-:false;type:timestamptz(6);index"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Model) Reset() {
	*x = Model{}
	mi := &file_hopeio_model_basic_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Model) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Model) ProtoMessage() {}

func (x *Model) ProtoReflect() protoreflect.Message {
	mi := &file_hopeio_model_basic_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Model.ProtoReflect.Descriptor instead.
func (*Model) Descriptor() ([]byte, []int) {
	return file_hopeio_model_basic_proto_rawDescGZIP(), []int{3}
}

func (x *Model) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Model) GetCreatedAt() *timestamp.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Model) GetUpdatedAt() *timestamp.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *Model) GetDeletedAt() *deletedAt.DeletedAt {
	if x != nil {
		return x.DeletedAt
	}
	return nil
}

var File_hopeio_model_basic_proto protoreflect.FileDescriptor

const file_hopeio_model_basic_proto_rawDesc = "" +
	"\n" +
	"\x18hopeio/model/basic.proto\x12\x05model\x1a\x1bhopeio/utils/patch/go.proto\x1a%hopeio/time/timestamp/timestamp.proto\x1a%hopeio/time/deletedAt/deletedAt.proto\"\xf4\x01\n" +
	"\fModelTimeStr\x12S\n" +
	"\tcreatedAt\x18\x01 \x01(\tB5ҵ\x031\xa2\x01.gorm:\"type:timestamptz(6);default:now();index\"R\tcreatedAt\x12?\n" +
	"\tupdatedAt\x18\x02 \x01(\tB!ҵ\x03\x1d\xa2\x01\x1agorm:\"type:timestamptz(6)\"R\tupdatedAt\x12N\n" +
	"\tdeletedAt\x18\x03 \x01(\tB0ҵ\x03,\xa2\x01)gorm:\"<-:false;type:timestamptz(6);index\"R\tdeletedAt\"\xb3\x02\n" +
	"\tModelTime\x12i\n" +
	"\tcreatedAt\x18\x01 \x01(\v2\x14.timestamp.TimestampB5ҵ\x031\xa2\x01.gorm:\"type:timestamptz(6);default:now();index\"R\tcreatedAt\x12U\n" +
	"\tupdatedAt\x18\x02 \x01(\v2\x14.timestamp.TimestampB!ҵ\x03\x1d\xa2\x01\x1agorm:\"type:timestamptz(6)\"R\tupdatedAt\x12d\n" +
	"\tdeletedAt\x18\x03 \x01(\v2\x14.deletedAt.DeletedAtB0ҵ\x03,\xa2\x01)gorm:\"<-:false;type:timestamptz(6);index\"R\tdeletedAt\"\xf4\x01\n" +
	"\fModelTimeInt\x12S\n" +
	"\tcreatedAt\x18\x01 \x01(\x03B5ҵ\x031\xa2\x01.gorm:\"type:timestamptz(6);default:now();index\"R\tcreatedAt\x12?\n" +
	"\tupdatedAt\x18\x02 \x01(\x03B!ҵ\x03\x1d\xa2\x01\x1agorm:\"type:timestamptz(6)\"R\tupdatedAt\x12N\n" +
	"\tdeletedAt\x18\x03 \x01(\x03B0ҵ\x03,\xa2\x01)gorm:\"<-:false;type:timestamptz(6);index\"R\tdeletedAt\"\xd3\x02\n" +
	"\x05Model\x12(\n" +
	"\x02id\x18\x01 \x01(\x04B\x18ҵ\x03\x14\xa2\x01\x11gorm:\"primaryKey\"R\x02id\x12c\n" +
	"\tcreatedAt\x18\x02 \x01(\v2\x14.timestamp.TimestampB/ҵ\x03+\xa2\x01(gorm:\"type:timestamptz(6);default:now()\"R\tcreatedAt\x12U\n" +
	"\tupdatedAt\x18\x03 \x01(\v2\x14.timestamp.TimestampB!ҵ\x03\x1d\xa2\x01\x1agorm:\"type:timestamptz(6)\"R\tupdatedAt\x12d\n" +
	"\tdeletedAt\x18\x04 \x01(\v2\x14.deletedAt.DeletedAtB0ҵ\x03,\xa2\x01)gorm:\"<-:false;type:timestamptz(6);index\"R\tdeletedAtB>\n" +
	"\x18xyz.hoper.protobuf.modelP\x01Z github.com/hopeio/protobuf/modelb\x06proto3"

var (
	file_hopeio_model_basic_proto_rawDescOnce sync.Once
	file_hopeio_model_basic_proto_rawDescData []byte
)

func file_hopeio_model_basic_proto_rawDescGZIP() []byte {
	file_hopeio_model_basic_proto_rawDescOnce.Do(func() {
		file_hopeio_model_basic_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_hopeio_model_basic_proto_rawDesc), len(file_hopeio_model_basic_proto_rawDesc)))
	})
	return file_hopeio_model_basic_proto_rawDescData
}

var file_hopeio_model_basic_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_hopeio_model_basic_proto_goTypes = []any{
	(*ModelTimeStr)(nil),        // 0: model.ModelTimeStr
	(*ModelTime)(nil),           // 1: model.ModelTime
	(*ModelTimeInt)(nil),        // 2: model.ModelTimeInt
	(*Model)(nil),               // 3: model.Model
	(*timestamp.Timestamp)(nil), // 4: timestamp.Timestamp
	(*deletedAt.DeletedAt)(nil), // 5: deletedAt.DeletedAt
}
var file_hopeio_model_basic_proto_depIdxs = []int32{
	4, // 0: model.ModelTime.createdAt:type_name -> timestamp.Timestamp
	4, // 1: model.ModelTime.updatedAt:type_name -> timestamp.Timestamp
	5, // 2: model.ModelTime.deletedAt:type_name -> deletedAt.DeletedAt
	4, // 3: model.Model.createdAt:type_name -> timestamp.Timestamp
	4, // 4: model.Model.updatedAt:type_name -> timestamp.Timestamp
	5, // 5: model.Model.deletedAt:type_name -> deletedAt.DeletedAt
	6, // [6:6] is the sub-list for method output_type
	6, // [6:6] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_hopeio_model_basic_proto_init() }
func file_hopeio_model_basic_proto_init() {
	if File_hopeio_model_basic_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_hopeio_model_basic_proto_rawDesc), len(file_hopeio_model_basic_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_hopeio_model_basic_proto_goTypes,
		DependencyIndexes: file_hopeio_model_basic_proto_depIdxs,
		MessageInfos:      file_hopeio_model_basic_proto_msgTypes,
	}.Build()
	File_hopeio_model_basic_proto = out.File
	file_hopeio_model_basic_proto_goTypes = nil
	file_hopeio_model_basic_proto_depIdxs = nil
}
