//
// Copyright 2024 hopeio. All rights reserved.
// Licensed under the MIT License that can be found in the LICENSE file.
// @Created by jyb

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: hopeio/model/gorm.proto

package model

import (
	_ "github.com/alta/protopatch/patch/gopb"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DeletedAt struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Mills         int64                  `protobuf:"varint,1,opt,name=mills,proto3" json:"mills,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeletedAt) Reset() {
	*x = DeletedAt{}
	mi := &file_hopeio_model_gorm_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeletedAt) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeletedAt) ProtoMessage() {}

func (x *DeletedAt) ProtoReflect() protoreflect.Message {
	mi := &file_hopeio_model_gorm_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeletedAt.ProtoReflect.Descriptor instead.
func (*DeletedAt) Descriptor() ([]byte, []int) {
	return file_hopeio_model_gorm_proto_rawDescGZIP(), []int{0}
}

func (x *DeletedAt) GetMills() int64 {
	if x != nil {
		return x.Mills
	}
	return 0
}

// [(go.field) = {tags:'json:",inline" gorm:"embedded"', embed:true}]
type ModelTime struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CreatedAt     int64                  `protobuf:"varint,1,opt,name=createdAt,proto3" json:"createdAt,omitempty" gorm:"serializer:unix_milli_time;type:timestamptz(6);default:now();index"`
	UpdatedAt     int64                  `protobuf:"varint,2,opt,name=updatedAt,proto3" json:"updatedAt,omitempty" gorm:"serializer:unix_milli_time;type:timestamptz(6)"`
	DeletedAt     *DeletedAt             `protobuf:"bytes,3,opt,name=deletedAt,proto3" json:"deletedAt,omitempty" gorm:"<-:false;type:timestamptz(6);index"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ModelTime) Reset() {
	*x = ModelTime{}
	mi := &file_hopeio_model_gorm_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ModelTime) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ModelTime) ProtoMessage() {}

func (x *ModelTime) ProtoReflect() protoreflect.Message {
	mi := &file_hopeio_model_gorm_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ModelTime.ProtoReflect.Descriptor instead.
func (*ModelTime) Descriptor() ([]byte, []int) {
	return file_hopeio_model_gorm_proto_rawDescGZIP(), []int{1}
}

func (x *ModelTime) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *ModelTime) GetUpdatedAt() int64 {
	if x != nil {
		return x.UpdatedAt
	}
	return 0
}

func (x *ModelTime) GetDeletedAt() *DeletedAt {
	if x != nil {
		return x.DeletedAt
	}
	return nil
}

// [(go.field) = {tags:'json:",inline" gorm:"embedded"'}]
type Model struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty" gorm:"primaryKey"`
	CreatedAt     int64                  `protobuf:"varint,2,opt,name=createdAt,proto3" json:"createdAt,omitempty" gorm:"serializer:unix_milli_time;type:timestamptz(6);default:now()"`
	UpdatedAt     int64                  `protobuf:"varint,3,opt,name=updatedAt,proto3" json:"updatedAt,omitempty" gorm:"serializer:unix_milli_time;type:timestamptz(6)"`
	DeletedAt     *DeletedAt             `protobuf:"bytes,4,opt,name=deletedAt,proto3" json:"deletedAt,omitempty" gorm:"<-:false;type:timestamptz(6);index"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Model) Reset() {
	*x = Model{}
	mi := &file_hopeio_model_gorm_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Model) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Model) ProtoMessage() {}

func (x *Model) ProtoReflect() protoreflect.Message {
	mi := &file_hopeio_model_gorm_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Model.ProtoReflect.Descriptor instead.
func (*Model) Descriptor() ([]byte, []int) {
	return file_hopeio_model_gorm_proto_rawDescGZIP(), []int{2}
}

func (x *Model) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Model) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *Model) GetUpdatedAt() int64 {
	if x != nil {
		return x.UpdatedAt
	}
	return 0
}

func (x *Model) GetDeletedAt() *DeletedAt {
	if x != nil {
		return x.DeletedAt
	}
	return nil
}

var File_hopeio_model_gorm_proto protoreflect.FileDescriptor

const file_hopeio_model_gorm_proto_rawDesc = "" +
	"\n" +
	"\x17hopeio/model/gorm.proto\x12\x05model\x1a\x0epatch/go.proto\"!\n" +
	"\tDeletedAt\x12\x14\n" +
	"\x05mills\x18\x01 \x01(\x03R\x05mills\"\xb9\x02\n" +
	"\tModelTime\x12n\n" +
	"\tcreatedAt\x18\x01 \x01(\x03BPʵ\x03L\xa2\x01Igorm:\"serializer:unix_milli_time;type:timestamptz(6);default:now();index\"R\tcreatedAt\x12Z\n" +
	"\tupdatedAt\x18\x02 \x01(\x03B<ʵ\x038\xa2\x015gorm:\"serializer:unix_milli_time;type:timestamptz(6)\"R\tupdatedAt\x12`\n" +
	"\tdeletedAt\x18\x03 \x01(\v2\x10.model.DeletedAtB0ʵ\x03,\xa2\x01)gorm:\"<-:false;type:timestamptz(6);index\"R\tdeletedAt\"\xd9\x02\n" +
	"\x05Model\x12(\n" +
	"\x02id\x18\x01 \x01(\x04B\x18ʵ\x03\x14\xa2\x01\x11gorm:\"primaryKey\"R\x02id\x12h\n" +
	"\tcreatedAt\x18\x02 \x01(\x03BJʵ\x03F\xa2\x01Cgorm:\"serializer:unix_milli_time;type:timestamptz(6);default:now()\"R\tcreatedAt\x12Z\n" +
	"\tupdatedAt\x18\x03 \x01(\x03B<ʵ\x038\xa2\x015gorm:\"serializer:unix_milli_time;type:timestamptz(6)\"R\tupdatedAt\x12`\n" +
	"\tdeletedAt\x18\x04 \x01(\v2\x10.model.DeletedAtB0ʵ\x03,\xa2\x01)gorm:\"<-:false;type:timestamptz(6);index\"R\tdeletedAtB>\n" +
	"\x18xyz.hoper.protobuf.modelP\x01Z github.com/hopeio/protobuf/modelb\x06proto3"

var (
	file_hopeio_model_gorm_proto_rawDescOnce sync.Once
	file_hopeio_model_gorm_proto_rawDescData []byte
)

func file_hopeio_model_gorm_proto_rawDescGZIP() []byte {
	file_hopeio_model_gorm_proto_rawDescOnce.Do(func() {
		file_hopeio_model_gorm_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_hopeio_model_gorm_proto_rawDesc), len(file_hopeio_model_gorm_proto_rawDesc)))
	})
	return file_hopeio_model_gorm_proto_rawDescData
}

var file_hopeio_model_gorm_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_hopeio_model_gorm_proto_goTypes = []any{
	(*DeletedAt)(nil), // 0: model.DeletedAt
	(*ModelTime)(nil), // 1: model.ModelTime
	(*Model)(nil),     // 2: model.Model
}
var file_hopeio_model_gorm_proto_depIdxs = []int32{
	0, // 0: model.ModelTime.deletedAt:type_name -> model.DeletedAt
	0, // 1: model.Model.deletedAt:type_name -> model.DeletedAt
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_hopeio_model_gorm_proto_init() }
func file_hopeio_model_gorm_proto_init() {
	if File_hopeio_model_gorm_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_hopeio_model_gorm_proto_rawDesc), len(file_hopeio_model_gorm_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_hopeio_model_gorm_proto_goTypes,
		DependencyIndexes: file_hopeio_model_gorm_proto_depIdxs,
		MessageInfos:      file_hopeio_model_gorm_proto_msgTypes,
	}.Build()
	File_hopeio_model_gorm_proto = out.File
	file_hopeio_model_gorm_proto_goTypes = nil
	file_hopeio_model_gorm_proto_depIdxs = nil
}
