//
// Copyright 2024 hopeio. All rights reserved.
// Licensed under the MIT License that can be found in the LICENSE file.
// @Created by jyb

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.32.0
// source: hopeio/model/model.proto

package model

import (
	_ "github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-openapiv2/options"
	_ "github.com/hopeio/protobuf/time/deletedAt"
	_ "github.com/hopeio/protobuf/time/timestamp"
	_ "github.com/hopeio/protobuf/utils/patch"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Enum struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty" gorm:"primaryKey"`
	Group         uint64                 `protobuf:"varint,2,opt,name=group,proto3" json:"group,omitempty" gorm:"size:20"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Type          uint32                 `protobuf:"varint,4,opt,name=type,proto3" json:"type,omitempty" comment:"类型"`
	Status        uint32                 `protobuf:"varint,5,opt,name=status,proto3" json:"status,omitempty" gorm:"type:int2;default:0"`
	ModelTime     *ModelTime             `protobuf:"bytes,6,opt,name=modelTime,proto3" json:"modelTime,inline" gorm:"embedded"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Enum) Reset() {
	*x = Enum{}
	mi := &file_hopeio_model_model_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Enum) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Enum) ProtoMessage() {}

func (x *Enum) ProtoReflect() protoreflect.Message {
	mi := &file_hopeio_model_model_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Enum.ProtoReflect.Descriptor instead.
func (*Enum) Descriptor() ([]byte, []int) {
	return file_hopeio_model_model_proto_rawDescGZIP(), []int{0}
}

func (x *Enum) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Enum) GetGroup() uint64 {
	if x != nil {
		return x.Group
	}
	return 0
}

func (x *Enum) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Enum) GetType() uint32 {
	if x != nil {
		return x.Type
	}
	return 0
}

func (x *Enum) GetStatus() uint32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *Enum) GetModelTime() *ModelTime {
	if x != nil {
		return x.ModelTime
	}
	return nil
}

type EnumValue struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty" gorm:"primaryKey"`
	EnumId        uint64                 `protobuf:"varint,2,opt,name=enumId,proto3" json:"enumId,omitempty"`
	Index         uint64                 `protobuf:"varint,3,opt,name=index,proto3" json:"index,omitempty" gorm:"comment:index"`
	Value         string                 `protobuf:"bytes,4,opt,name=value,proto3" json:"value,omitempty" comment:"值"`
	Status        uint32                 `protobuf:"varint,5,opt,name=status,proto3" json:"status,omitempty" gorm:"type:int2;default:0"`
	ModelTime     *ModelTime             `protobuf:"bytes,6,opt,name=modelTime,proto3" json:"modelTime,inline" gorm:"embedded"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnumValue) Reset() {
	*x = EnumValue{}
	mi := &file_hopeio_model_model_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnumValue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnumValue) ProtoMessage() {}

func (x *EnumValue) ProtoReflect() protoreflect.Message {
	mi := &file_hopeio_model_model_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnumValue.ProtoReflect.Descriptor instead.
func (*EnumValue) Descriptor() ([]byte, []int) {
	return file_hopeio_model_model_proto_rawDescGZIP(), []int{1}
}

func (x *EnumValue) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *EnumValue) GetEnumId() uint64 {
	if x != nil {
		return x.EnumId
	}
	return 0
}

func (x *EnumValue) GetIndex() uint64 {
	if x != nil {
		return x.Index
	}
	return 0
}

func (x *EnumValue) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *EnumValue) GetStatus() uint32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *EnumValue) GetModelTime() *ModelTime {
	if x != nil {
		return x.ModelTime
	}
	return nil
}

type Area struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          uint64                 `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty" gorm:"primaryKey"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Level         int32                  `protobuf:"varint,3,opt,name=level,proto3" json:"level,omitempty"`
	Pcode         uint64                 `protobuf:"varint,4,opt,name=pcode,proto3" json:"pcode,omitempty"`
	ModelTime     *ModelTime             `protobuf:"bytes,5,opt,name=modelTime,proto3" json:"modelTime,inline" gorm:"embedded"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Area) Reset() {
	*x = Area{}
	mi := &file_hopeio_model_model_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Area) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Area) ProtoMessage() {}

func (x *Area) ProtoReflect() protoreflect.Message {
	mi := &file_hopeio_model_model_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Area.ProtoReflect.Descriptor instead.
func (*Area) Descriptor() ([]byte, []int) {
	return file_hopeio_model_model_proto_rawDescGZIP(), []int{2}
}

func (x *Area) GetCode() uint64 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *Area) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Area) GetLevel() int32 {
	if x != nil {
		return x.Level
	}
	return 0
}

func (x *Area) GetPcode() uint64 {
	if x != nil {
		return x.Pcode
	}
	return 0
}

func (x *Area) GetModelTime() *ModelTime {
	if x != nil {
		return x.ModelTime
	}
	return nil
}

type Attribute struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty" gorm:"primaryKey"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Status        uint32                 `protobuf:"varint,3,opt,name=status,proto3" json:"status,omitempty" gorm:"type:int2;default:0"`
	ModelTime     *ModelTime             `protobuf:"bytes,4,opt,name=modelTime,proto3" json:"modelTime,inline" gorm:"embedded"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Attribute) Reset() {
	*x = Attribute{}
	mi := &file_hopeio_model_model_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Attribute) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Attribute) ProtoMessage() {}

func (x *Attribute) ProtoReflect() protoreflect.Message {
	mi := &file_hopeio_model_model_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Attribute.ProtoReflect.Descriptor instead.
func (*Attribute) Descriptor() ([]byte, []int) {
	return file_hopeio_model_model_proto_rawDescGZIP(), []int{3}
}

func (x *Attribute) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Attribute) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Attribute) GetStatus() uint32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *Attribute) GetModelTime() *ModelTime {
	if x != nil {
		return x.ModelTime
	}
	return nil
}

type Dict struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty" gorm:"primaryKey"`
	Group         uint32                 `protobuf:"varint,2,opt,name=group,proto3" json:"group,omitempty"`
	Key           string                 `protobuf:"bytes,4,opt,name=key,proto3" json:"key,omitempty" gorm:"键"`
	Value         string                 `protobuf:"bytes,5,opt,name=value,proto3" json:"value,omitempty" comment:"值"`
	Type          uint32                 `protobuf:"varint,6,opt,name=type,proto3" json:"type,omitempty" comment:"类型"`
	Seq           uint32                 `protobuf:"varint,7,opt,name=seq,proto3" json:"seq,omitempty" comment:"顺序"`
	Status        uint32                 `protobuf:"varint,8,opt,name=status,proto3" json:"status,omitempty" gorm:"type:int2;default:0"`
	ModelTime     *ModelTime             `protobuf:"bytes,9,opt,name=modelTime,proto3" json:"modelTime,inline" gorm:"embedded"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Dict) Reset() {
	*x = Dict{}
	mi := &file_hopeio_model_model_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Dict) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Dict) ProtoMessage() {}

func (x *Dict) ProtoReflect() protoreflect.Message {
	mi := &file_hopeio_model_model_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Dict.ProtoReflect.Descriptor instead.
func (*Dict) Descriptor() ([]byte, []int) {
	return file_hopeio_model_model_proto_rawDescGZIP(), []int{4}
}

func (x *Dict) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Dict) GetGroup() uint32 {
	if x != nil {
		return x.Group
	}
	return 0
}

func (x *Dict) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *Dict) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *Dict) GetType() uint32 {
	if x != nil {
		return x.Type
	}
	return 0
}

func (x *Dict) GetSeq() uint32 {
	if x != nil {
		return x.Seq
	}
	return 0
}

func (x *Dict) GetStatus() uint32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *Dict) GetModelTime() *ModelTime {
	if x != nil {
		return x.ModelTime
	}
	return nil
}

type FrontRoute struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty" gorm:"primaryKey"`
	Path          string                 `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Redirect      string                 `protobuf:"bytes,4,opt,name=redirect,proto3" json:"redirect,omitempty"`
	Meta          *FrontRouteMeta        `protobuf:"bytes,5,opt,name=meta,proto3" json:"meta,inline" gorm:"embedded"`
	ParentId      uint64                 `protobuf:"varint,6,opt,name=parentId,proto3" json:"parentId,omitempty" gorm:"not null;default:0" comment:"父级id"`
	Children      []*FrontRoute          `protobuf:"bytes,7,rep,name=children,proto3" json:"children,omitempty" gorm:"foreignkey:ParentId"`
	ModelTime     *ModelTime             `protobuf:"bytes,8,opt,name=modelTime,proto3" json:"modelTime,inline" gorm:"embedded"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FrontRoute) Reset() {
	*x = FrontRoute{}
	mi := &file_hopeio_model_model_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FrontRoute) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FrontRoute) ProtoMessage() {}

func (x *FrontRoute) ProtoReflect() protoreflect.Message {
	mi := &file_hopeio_model_model_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FrontRoute.ProtoReflect.Descriptor instead.
func (*FrontRoute) Descriptor() ([]byte, []int) {
	return file_hopeio_model_model_proto_rawDescGZIP(), []int{5}
}

func (x *FrontRoute) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *FrontRoute) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *FrontRoute) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *FrontRoute) GetRedirect() string {
	if x != nil {
		return x.Redirect
	}
	return ""
}

func (x *FrontRoute) GetMeta() *FrontRouteMeta {
	if x != nil {
		return x.Meta
	}
	return nil
}

func (x *FrontRoute) GetParentId() uint64 {
	if x != nil {
		return x.ParentId
	}
	return 0
}

func (x *FrontRoute) GetChildren() []*FrontRoute {
	if x != nil {
		return x.Children
	}
	return nil
}

func (x *FrontRoute) GetModelTime() *ModelTime {
	if x != nil {
		return x.ModelTime
	}
	return nil
}

type FrontRouteMeta struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Title         string                 `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Icon          string                 `protobuf:"bytes,2,opt,name=icon,proto3" json:"icon,omitempty"`
	ShowLink      bool                   `protobuf:"varint,3,opt,name=showLink,proto3" json:"showLink,omitempty"`
	Rank          int32                  `protobuf:"varint,4,opt,name=rank,proto3" json:"rank,omitempty"`
	Roles         []string               `protobuf:"bytes,5,rep,name=roles,proto3" json:"roles,omitempty" gorm:"type:text[];serializer:string_array"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FrontRouteMeta) Reset() {
	*x = FrontRouteMeta{}
	mi := &file_hopeio_model_model_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FrontRouteMeta) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FrontRouteMeta) ProtoMessage() {}

func (x *FrontRouteMeta) ProtoReflect() protoreflect.Message {
	mi := &file_hopeio_model_model_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FrontRouteMeta.ProtoReflect.Descriptor instead.
func (*FrontRouteMeta) Descriptor() ([]byte, []int) {
	return file_hopeio_model_model_proto_rawDescGZIP(), []int{6}
}

func (x *FrontRouteMeta) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *FrontRouteMeta) GetIcon() string {
	if x != nil {
		return x.Icon
	}
	return ""
}

func (x *FrontRouteMeta) GetShowLink() bool {
	if x != nil {
		return x.ShowLink
	}
	return false
}

func (x *FrontRouteMeta) GetRank() int32 {
	if x != nil {
		return x.Rank
	}
	return 0
}

func (x *FrontRouteMeta) GetRoles() []string {
	if x != nil {
		return x.Roles
	}
	return nil
}

var File_hopeio_model_model_proto protoreflect.FileDescriptor

const file_hopeio_model_model_proto_rawDesc = "" +
	"\n" +
	"\x18hopeio/model/model.proto\x12\x05model\x1a\x1bhopeio/utils/patch/go.proto\x1a%hopeio/time/timestamp/timestamp.proto\x1a%hopeio/time/deletedAt/deletedAt.proto\x1a\x18hopeio/model/basic.proto\x1a.protoc-gen-openapiv2/options/annotations.proto\"\xd6\x02\n" +
	"\x04Enum\x12(\n" +
	"\x02id\x18\x01 \x01(\x04B\x18ҵ\x03\x14\xa2\x01\x11gorm:\"primaryKey\"R\x02id\x12+\n" +
	"\x05group\x18\x02 \x01(\x04B\x15ҵ\x03\x11\xa2\x01\x0egorm:\"size:20\"R\x05group\x12*\n" +
	"\x04name\x18\x03 \x01(\tB\x16ҵ\x03\x12\xa2\x01\x0fcomment:\"名称R\x04name\x12+\n" +
	"\x04type\x18\x04 \x01(\rB\x17ҵ\x03\x13\xa2\x01\x10comment:\"类型\"R\x04type\x12>\n" +
	"\x06status\x18\x05 \x01(\rB&\x92A\x02@\x01ҵ\x03\x1d\xa2\x01\x1agorm:\"type:int2;default:0\"R\x06status\x12^\n" +
	"\tmodelTime\x18\x06 \x01(\v2\x10.model.ModelTimeB.ҵ\x03*\xa2\x01'json:\"modelTime,inline\" gorm:\"embedded\"R\tmodelTime\"\xe6\x02\n" +
	"\tEnumValue\x12(\n" +
	"\x02id\x18\x01 \x01(\x04B\x18ҵ\x03\x14\xa2\x01\x11gorm:\"primaryKey\"R\x02id\x120\n" +
	"\x06enumId\x18\x02 \x01(\x04B\x18ҵ\x03\x14\xa2\x01\x11comment:\"枚举idR\x06enumId\x121\n" +
	"\x05index\x18\x03 \x01(\x04B\x1bҵ\x03\x17\xa2\x01\x14gorm:\"comment:index\"R\x05index\x12*\n" +
	"\x05value\x18\x04 \x01(\tB\x14ҵ\x03\x10\xa2\x01\rcomment:\"值\"R\x05value\x12>\n" +
	"\x06status\x18\x05 \x01(\rB&\x92A\x02@\x01ҵ\x03\x1d\xa2\x01\x1agorm:\"type:int2;default:0\"R\x06status\x12^\n" +
	"\tmodelTime\x18\x06 \x01(\v2\x10.model.ModelTimeB.ҵ\x03*\xa2\x01'json:\"modelTime,inline\" gorm:\"embedded\"R\tmodelTime\"\xd4\x01\n" +
	"\x04Area\x12,\n" +
	"\x04code\x18\x01 \x01(\x04B\x18ҵ\x03\x14\xa2\x01\x11gorm:\"primaryKey\"R\x04code\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x14\n" +
	"\x05level\x18\x03 \x01(\x05R\x05level\x12\x14\n" +
	"\x05pcode\x18\x04 \x01(\x04R\x05pcode\x12^\n" +
	"\tmodelTime\x18\x05 \x01(\v2\x10.model.ModelTimeB.ҵ\x03*\xa2\x01'json:\"modelTime,inline\" gorm:\"embedded\"R\tmodelTime\"\x81\x02\n" +
	"\tAttribute\x12(\n" +
	"\x02id\x18\x01 \x01(\x04B\x18ҵ\x03\x14\xa2\x01\x11gorm:\"primaryKey\"R\x02id\x12*\n" +
	"\x04name\x18\x02 \x01(\tB\x16ҵ\x03\x12\xa2\x01\x0fcomment:\"名称R\x04name\x12>\n" +
	"\x06status\x18\x03 \x01(\rB&\x92A\x02@\x01ҵ\x03\x1d\xa2\x01\x1agorm:\"type:int2;default:0\"R\x06status\x12^\n" +
	"\tmodelTime\x18\x04 \x01(\v2\x10.model.ModelTimeB.ҵ\x03*\xa2\x01'json:\"modelTime,inline\" gorm:\"embedded\"R\tmodelTime\"\xa4\x03\n" +
	"\x04Dict\x12(\n" +
	"\x02id\x18\x01 \x01(\x04B\x18ҵ\x03\x14\xa2\x01\x11gorm:\"primaryKey\"R\x02id\x12)\n" +
	"\x05group\x18\x02 \x01(\rB\x13ҵ\x03\x0f\xa2\x01\fcomment:\"组R\x05group\x12#\n" +
	"\x03key\x18\x04 \x01(\tB\x11ҵ\x03\r\xa2\x01\n" +
	"gorm:\"键\"R\x03key\x12*\n" +
	"\x05value\x18\x05 \x01(\tB\x14ҵ\x03\x10\xa2\x01\rcomment:\"值\"R\x05value\x12+\n" +
	"\x04type\x18\x06 \x01(\rB\x17ҵ\x03\x13\xa2\x01\x10comment:\"类型\"R\x04type\x12)\n" +
	"\x03seq\x18\a \x01(\rB\x17ҵ\x03\x13\xa2\x01\x10comment:\"顺序\"R\x03seq\x12>\n" +
	"\x06status\x18\b \x01(\rB&\x92A\x02@\x01ҵ\x03\x1d\xa2\x01\x1agorm:\"type:int2;default:0\"R\x06status\x12^\n" +
	"\tmodelTime\x18\t \x01(\v2\x10.model.ModelTimeB.ҵ\x03*\xa2\x01'json:\"modelTime,inline\" gorm:\"embedded\"R\tmodelTime\"\xd3\x03\n" +
	"\n" +
	"FrontRoute\x12(\n" +
	"\x02id\x18\x01 \x01(\x04B\x18ҵ\x03\x14\xa2\x01\x11gorm:\"primaryKey\"R\x02id\x12\x12\n" +
	"\x04path\x18\x02 \x01(\tR\x04path\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x1a\n" +
	"\bredirect\x18\x04 \x01(\tR\bredirect\x12T\n" +
	"\x04meta\x18\x05 \x01(\v2\x15.model.FrontRouteMetaB)ҵ\x03%\xa2\x01\"json:\"meta,inline\" gorm:\"embedded\"R\x04meta\x12O\n" +
	"\bparentId\x18\x06 \x01(\x04B3ҵ\x03/\xa2\x01,gorm:\"not null;default:0\" comment:\"父级id\"R\bparentId\x12P\n" +
	"\bchildren\x18\a \x03(\v2\x11.model.FrontRouteB!ҵ\x03\x1d\xa2\x01\x1agorm:\"foreignkey:ParentId\"R\bchildren\x12^\n" +
	"\tmodelTime\x18\b \x01(\v2\x10.model.ModelTimeB.ҵ\x03*\xa2\x01'json:\"modelTime,inline\" gorm:\"embedded\"R\tmodelTime\"\xb3\x01\n" +
	"\x0eFrontRouteMeta\x12\x14\n" +
	"\x05title\x18\x01 \x01(\tR\x05title\x12\x12\n" +
	"\x04icon\x18\x02 \x01(\tR\x04icon\x12\x1a\n" +
	"\bshowLink\x18\x03 \x01(\bR\bshowLink\x12\x12\n" +
	"\x04rank\x18\x04 \x01(\x05R\x04rank\x12G\n" +
	"\x05roles\x18\x05 \x03(\tB1ҵ\x03-\xa2\x01*gorm:\"type:text[];serializer:string_array\"R\x05rolesB>\n" +
	"\x18xyz.hoper.protobuf.modelP\x01Z github.com/hopeio/protobuf/modelb\x06proto3"

var (
	file_hopeio_model_model_proto_rawDescOnce sync.Once
	file_hopeio_model_model_proto_rawDescData []byte
)

func file_hopeio_model_model_proto_rawDescGZIP() []byte {
	file_hopeio_model_model_proto_rawDescOnce.Do(func() {
		file_hopeio_model_model_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_hopeio_model_model_proto_rawDesc), len(file_hopeio_model_model_proto_rawDesc)))
	})
	return file_hopeio_model_model_proto_rawDescData
}

var file_hopeio_model_model_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_hopeio_model_model_proto_goTypes = []any{
	(*Enum)(nil),           // 0: model.Enum
	(*EnumValue)(nil),      // 1: model.EnumValue
	(*Area)(nil),           // 2: model.Area
	(*Attribute)(nil),      // 3: model.Attribute
	(*Dict)(nil),           // 4: model.Dict
	(*FrontRoute)(nil),     // 5: model.FrontRoute
	(*FrontRouteMeta)(nil), // 6: model.FrontRouteMeta
	(*ModelTime)(nil),      // 7: model.ModelTime
}
var file_hopeio_model_model_proto_depIdxs = []int32{
	7, // 0: model.Enum.modelTime:type_name -> model.ModelTime
	7, // 1: model.EnumValue.modelTime:type_name -> model.ModelTime
	7, // 2: model.Area.modelTime:type_name -> model.ModelTime
	7, // 3: model.Attribute.modelTime:type_name -> model.ModelTime
	7, // 4: model.Dict.modelTime:type_name -> model.ModelTime
	6, // 5: model.FrontRoute.meta:type_name -> model.FrontRouteMeta
	5, // 6: model.FrontRoute.children:type_name -> model.FrontRoute
	7, // 7: model.FrontRoute.modelTime:type_name -> model.ModelTime
	8, // [8:8] is the sub-list for method output_type
	8, // [8:8] is the sub-list for method input_type
	8, // [8:8] is the sub-list for extension type_name
	8, // [8:8] is the sub-list for extension extendee
	0, // [0:8] is the sub-list for field type_name
}

func init() { file_hopeio_model_model_proto_init() }
func file_hopeio_model_model_proto_init() {
	if File_hopeio_model_model_proto != nil {
		return
	}
	file_hopeio_model_basic_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_hopeio_model_model_proto_rawDesc), len(file_hopeio_model_model_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_hopeio_model_model_proto_goTypes,
		DependencyIndexes: file_hopeio_model_model_proto_depIdxs,
		MessageInfos:      file_hopeio_model_model_proto_msgTypes,
	}.Build()
	File_hopeio_model_model_proto = out.File
	file_hopeio_model_model_proto_goTypes = nil
	file_hopeio_model_model_proto_depIdxs = nil
}
