//
// Copyright 2024 hopeio. All rights reserved.
// Licensed under the MIT License that can be found in the LICENSE file.
// @Created by jyb

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.32.0
// source: hopeio/model/model.proto

package model

import (
	_ "github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-openapiv2/options"
	_ "github.com/hopeio/protobuf/time/deletedAt"
	_ "github.com/hopeio/protobuf/time/timestamp"
	_ "github.com/hopeio/protobuf/utils/patch"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Enum struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Basic         *Model                 `protobuf:"bytes,1,opt,name=basic,proto3" json:"basic,inline" gorm:"embedded"`
	Group         uint64                 `protobuf:"varint,2,opt,name=group,proto3" json:"group,omitempty" gorm:"size:20"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Type          uint32                 `protobuf:"varint,4,opt,name=type,proto3" json:"type,omitempty" comment:"类型"`
	Status        uint32                 `protobuf:"varint,8,opt,name=status,proto3" json:"status,omitempty" gorm:"type:int2;default:0"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Enum) Reset() {
	*x = Enum{}
	mi := &file_hopeio_model_model_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Enum) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Enum) ProtoMessage() {}

func (x *Enum) ProtoReflect() protoreflect.Message {
	mi := &file_hopeio_model_model_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Enum.ProtoReflect.Descriptor instead.
func (*Enum) Descriptor() ([]byte, []int) {
	return file_hopeio_model_model_proto_rawDescGZIP(), []int{0}
}

func (x *Enum) GetBasic() *Model {
	if x != nil {
		return x.Basic
	}
	return nil
}

func (x *Enum) GetGroup() uint64 {
	if x != nil {
		return x.Group
	}
	return 0
}

func (x *Enum) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Enum) GetType() uint32 {
	if x != nil {
		return x.Type
	}
	return 0
}

func (x *Enum) GetStatus() uint32 {
	if x != nil {
		return x.Status
	}
	return 0
}

type EnumValue struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Basic         *Model                 `protobuf:"bytes,1,opt,name=basic,proto3" json:"basic,inline" gorm:"embedded"`
	EnumId        uint64                 `protobuf:"varint,2,opt,name=enumId,proto3" json:"enumId,omitempty"`
	Index         uint64                 `protobuf:"varint,3,opt,name=index,proto3" json:"index,omitempty" gorm:"comment:index"`
	Value         string                 `protobuf:"bytes,4,opt,name=value,proto3" json:"value,omitempty" comment:"值"`
	Status        uint32                 `protobuf:"varint,8,opt,name=status,proto3" json:"status,omitempty" gorm:"type:int2;default:0"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnumValue) Reset() {
	*x = EnumValue{}
	mi := &file_hopeio_model_model_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnumValue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnumValue) ProtoMessage() {}

func (x *EnumValue) ProtoReflect() protoreflect.Message {
	mi := &file_hopeio_model_model_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnumValue.ProtoReflect.Descriptor instead.
func (*EnumValue) Descriptor() ([]byte, []int) {
	return file_hopeio_model_model_proto_rawDescGZIP(), []int{1}
}

func (x *EnumValue) GetBasic() *Model {
	if x != nil {
		return x.Basic
	}
	return nil
}

func (x *EnumValue) GetEnumId() uint64 {
	if x != nil {
		return x.EnumId
	}
	return 0
}

func (x *EnumValue) GetIndex() uint64 {
	if x != nil {
		return x.Index
	}
	return 0
}

func (x *EnumValue) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *EnumValue) GetStatus() uint32 {
	if x != nil {
		return x.Status
	}
	return 0
}

type Area struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          uint64                 `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty" gorm:"primaryKey"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Level         int32                  `protobuf:"varint,3,opt,name=level,proto3" json:"level,omitempty"`
	Pcode         uint64                 `protobuf:"varint,4,opt,name=pcode,proto3" json:"pcode,omitempty"`
	Time          *ModelTime             `protobuf:"bytes,5,opt,name=time,proto3" json:"time,inline" gorm:"embedded"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Area) Reset() {
	*x = Area{}
	mi := &file_hopeio_model_model_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Area) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Area) ProtoMessage() {}

func (x *Area) ProtoReflect() protoreflect.Message {
	mi := &file_hopeio_model_model_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Area.ProtoReflect.Descriptor instead.
func (*Area) Descriptor() ([]byte, []int) {
	return file_hopeio_model_model_proto_rawDescGZIP(), []int{2}
}

func (x *Area) GetCode() uint64 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *Area) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Area) GetLevel() int32 {
	if x != nil {
		return x.Level
	}
	return 0
}

func (x *Area) GetPcode() uint64 {
	if x != nil {
		return x.Pcode
	}
	return 0
}

func (x *Area) GetTime() *ModelTime {
	if x != nil {
		return x.Time
	}
	return nil
}

type Attribute struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Basic         *Model                 `protobuf:"bytes,1,opt,name=basic,proto3" json:"basic,inline" gorm:"embedded"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Status        uint32                 `protobuf:"varint,18,opt,name=status,proto3" json:"status,omitempty" gorm:"type:int2;default:0"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Attribute) Reset() {
	*x = Attribute{}
	mi := &file_hopeio_model_model_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Attribute) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Attribute) ProtoMessage() {}

func (x *Attribute) ProtoReflect() protoreflect.Message {
	mi := &file_hopeio_model_model_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Attribute.ProtoReflect.Descriptor instead.
func (*Attribute) Descriptor() ([]byte, []int) {
	return file_hopeio_model_model_proto_rawDescGZIP(), []int{3}
}

func (x *Attribute) GetBasic() *Model {
	if x != nil {
		return x.Basic
	}
	return nil
}

func (x *Attribute) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Attribute) GetStatus() uint32 {
	if x != nil {
		return x.Status
	}
	return 0
}

type Dict struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Basic         *Model                 `protobuf:"bytes,1,opt,name=basic,proto3" json:"basic,inline" gorm:"embedded"`
	Group         uint32                 `protobuf:"varint,2,opt,name=group,proto3" json:"group,omitempty"`
	Key           string                 `protobuf:"bytes,4,opt,name=key,proto3" json:"key,omitempty" gorm:"键"`
	Value         string                 `protobuf:"bytes,5,opt,name=value,proto3" json:"value,omitempty" comment:"值"`
	Type          uint32                 `protobuf:"varint,6,opt,name=type,proto3" json:"type,omitempty" comment:"类型"`
	Seq           uint32                 `protobuf:"varint,7,opt,name=seq,proto3" json:"seq,omitempty" comment:"顺序"`
	Status        uint32                 `protobuf:"varint,8,opt,name=status,proto3" json:"status,omitempty" gorm:"type:int2;default:0"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Dict) Reset() {
	*x = Dict{}
	mi := &file_hopeio_model_model_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Dict) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Dict) ProtoMessage() {}

func (x *Dict) ProtoReflect() protoreflect.Message {
	mi := &file_hopeio_model_model_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Dict.ProtoReflect.Descriptor instead.
func (*Dict) Descriptor() ([]byte, []int) {
	return file_hopeio_model_model_proto_rawDescGZIP(), []int{4}
}

func (x *Dict) GetBasic() *Model {
	if x != nil {
		return x.Basic
	}
	return nil
}

func (x *Dict) GetGroup() uint32 {
	if x != nil {
		return x.Group
	}
	return 0
}

func (x *Dict) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *Dict) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *Dict) GetType() uint32 {
	if x != nil {
		return x.Type
	}
	return 0
}

func (x *Dict) GetSeq() uint32 {
	if x != nil {
		return x.Seq
	}
	return 0
}

func (x *Dict) GetStatus() uint32 {
	if x != nil {
		return x.Status
	}
	return 0
}

var File_hopeio_model_model_proto protoreflect.FileDescriptor

const file_hopeio_model_model_proto_rawDesc = "" +
	"\n" +
	"\x18hopeio/model/model.proto\x12\x05model\x1a\x1bhopeio/utils/patch/go.proto\x1a%hopeio/time/timestamp/timestamp.proto\x1a%hopeio/time/deletedAt/deletedAt.proto\x1a\x18hopeio/model/basic.proto\x1a.protoc-gen-openapiv2/options/annotations.proto\"\x9c\x02\n" +
	"\x04Enum\x12N\n" +
	"\x05basic\x18\x01 \x01(\v2\f.model.ModelB*ҵ\x03&\xa2\x01#json:\"basic,inline\" gorm:\"embedded\"R\x05basic\x12+\n" +
	"\x05group\x18\x02 \x01(\x04B\x15ҵ\x03\x11\xa2\x01\x0egorm:\"size:20\"R\x05group\x12*\n" +
	"\x04name\x18\x03 \x01(\tB\x16ҵ\x03\x12\xa2\x01\x0fcomment:\"名称R\x04name\x12+\n" +
	"\x04type\x18\x04 \x01(\rB\x17ҵ\x03\x13\xa2\x01\x10comment:\"类型\"R\x04type\x12>\n" +
	"\x06status\x18\b \x01(\rB&\x92A\x02@\x01ҵ\x03\x1d\xa2\x01\x1agorm:\"type:int2;default:0\"R\x06status\"\xac\x02\n" +
	"\tEnumValue\x12N\n" +
	"\x05basic\x18\x01 \x01(\v2\f.model.ModelB*ҵ\x03&\xa2\x01#json:\"basic,inline\" gorm:\"embedded\"R\x05basic\x120\n" +
	"\x06enumId\x18\x02 \x01(\x04B\x18ҵ\x03\x14\xa2\x01\x11comment:\"枚举idR\x06enumId\x121\n" +
	"\x05index\x18\x03 \x01(\x04B\x1bҵ\x03\x17\xa2\x01\x14gorm:\"comment:index\"R\x05index\x12*\n" +
	"\x05value\x18\x04 \x01(\tB\x14ҵ\x03\x10\xa2\x01\rcomment:\"值\"R\x05value\x12>\n" +
	"\x06status\x18\b \x01(\rB&\x92A\x02@\x01ҵ\x03\x1d\xa2\x01\x1agorm:\"type:int2;default:0\"R\x06status\"\xc5\x01\n" +
	"\x04Area\x12,\n" +
	"\x04code\x18\x01 \x01(\x04B\x18ҵ\x03\x14\xa2\x01\x11gorm:\"primaryKey\"R\x04code\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x14\n" +
	"\x05level\x18\x03 \x01(\x05R\x05level\x12\x14\n" +
	"\x05pcode\x18\x04 \x01(\x04R\x05pcode\x12O\n" +
	"\x04time\x18\x05 \x01(\v2\x10.model.ModelTimeB)ҵ\x03%\xa2\x01\"json:\"time,inline\" gorm:\"embedded\"R\x04time\"\xc7\x01\n" +
	"\tAttribute\x12N\n" +
	"\x05basic\x18\x01 \x01(\v2\f.model.ModelB*ҵ\x03&\xa2\x01#json:\"basic,inline\" gorm:\"embedded\"R\x05basic\x12*\n" +
	"\x04name\x18\x02 \x01(\tB\x16ҵ\x03\x12\xa2\x01\x0fcomment:\"名称R\x04name\x12>\n" +
	"\x06status\x18\x12 \x01(\rB&\x92A\x02@\x01ҵ\x03\x1d\xa2\x01\x1agorm:\"type:int2;default:0\"R\x06status\"\xea\x02\n" +
	"\x04Dict\x12N\n" +
	"\x05basic\x18\x01 \x01(\v2\f.model.ModelB*ҵ\x03&\xa2\x01#json:\"basic,inline\" gorm:\"embedded\"R\x05basic\x12)\n" +
	"\x05group\x18\x02 \x01(\rB\x13ҵ\x03\x0f\xa2\x01\fcomment:\"组R\x05group\x12#\n" +
	"\x03key\x18\x04 \x01(\tB\x11ҵ\x03\r\xa2\x01\n" +
	"gorm:\"键\"R\x03key\x12*\n" +
	"\x05value\x18\x05 \x01(\tB\x14ҵ\x03\x10\xa2\x01\rcomment:\"值\"R\x05value\x12+\n" +
	"\x04type\x18\x06 \x01(\rB\x17ҵ\x03\x13\xa2\x01\x10comment:\"类型\"R\x04type\x12)\n" +
	"\x03seq\x18\a \x01(\rB\x17ҵ\x03\x13\xa2\x01\x10comment:\"顺序\"R\x03seq\x12>\n" +
	"\x06status\x18\b \x01(\rB&\x92A\x02@\x01ҵ\x03\x1d\xa2\x01\x1agorm:\"type:int2;default:0\"R\x06statusB>\n" +
	"\x18xyz.hoper.protobuf.modelP\x01Z github.com/hopeio/protobuf/modelb\x06proto3"

var (
	file_hopeio_model_model_proto_rawDescOnce sync.Once
	file_hopeio_model_model_proto_rawDescData []byte
)

func file_hopeio_model_model_proto_rawDescGZIP() []byte {
	file_hopeio_model_model_proto_rawDescOnce.Do(func() {
		file_hopeio_model_model_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_hopeio_model_model_proto_rawDesc), len(file_hopeio_model_model_proto_rawDesc)))
	})
	return file_hopeio_model_model_proto_rawDescData
}

var file_hopeio_model_model_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_hopeio_model_model_proto_goTypes = []any{
	(*Enum)(nil),      // 0: model.Enum
	(*EnumValue)(nil), // 1: model.EnumValue
	(*Area)(nil),      // 2: model.Area
	(*Attribute)(nil), // 3: model.Attribute
	(*Dict)(nil),      // 4: model.Dict
	(*Model)(nil),     // 5: model.Model
	(*ModelTime)(nil), // 6: model.ModelTime
}
var file_hopeio_model_model_proto_depIdxs = []int32{
	5, // 0: model.Enum.basic:type_name -> model.Model
	5, // 1: model.EnumValue.basic:type_name -> model.Model
	6, // 2: model.Area.time:type_name -> model.ModelTime
	5, // 3: model.Attribute.basic:type_name -> model.Model
	5, // 4: model.Dict.basic:type_name -> model.Model
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_hopeio_model_model_proto_init() }
func file_hopeio_model_model_proto_init() {
	if File_hopeio_model_model_proto != nil {
		return
	}
	file_hopeio_model_basic_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_hopeio_model_model_proto_rawDesc), len(file_hopeio_model_model_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_hopeio_model_model_proto_goTypes,
		DependencyIndexes: file_hopeio_model_model_proto_depIdxs,
		MessageInfos:      file_hopeio_model_model_proto_msgTypes,
	}.Build()
	File_hopeio_model_model_proto = out.File
	file_hopeio_model_model_proto_goTypes = nil
	file_hopeio_model_model_proto_depIdxs = nil
}
