//
// Copyright 2024 hopeio. All rights reserved.
// Licensed under the MIT License that can be found in the LICENSE file.
// @Created by jyb

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.1
// source: hopeio/model/table.proto

package model

import (
	_ "github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-openapiv2/options"
	_ "github.com/hopeio/protobuf/time/deletedAt"
	_ "github.com/hopeio/protobuf/time/timestamp"
	_ "github.com/hopeio/protobuf/utils/patch"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TableMeta struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Model         *Model                 `protobuf:"bytes,1,opt,name=model,proto3" json:",inline" gorm:"embedded"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Status        uint32                 `protobuf:"varint,3,opt,name=status,proto3" json:"status,omitempty" gorm:"type:int2;default:0"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TableMeta) Reset() {
	*x = TableMeta{}
	mi := &file_hopeio_model_table_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TableMeta) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TableMeta) ProtoMessage() {}

func (x *TableMeta) ProtoReflect() protoreflect.Message {
	mi := &file_hopeio_model_table_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TableMeta.ProtoReflect.Descriptor instead.
func (*TableMeta) Descriptor() ([]byte, []int) {
	return file_hopeio_model_table_proto_rawDescGZIP(), []int{0}
}

func (x *TableMeta) GetModel() *Model {
	if x != nil {
		return x.Model
	}
	return nil
}

func (x *TableMeta) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *TableMeta) GetStatus() uint32 {
	if x != nil {
		return x.Status
	}
	return 0
}

type TableColumn struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Model         *Model                 `protobuf:"bytes,1,opt,name=model,proto3" json:",inline" gorm:"embedded"`
	TableId       uint64                 `protobuf:"varint,2,opt,name=tableId,proto3" json:"tableId,omitempty" gorm:"comment:tableId"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Type          uint32                 `protobuf:"varint,4,opt,name=type,proto3" json:"type,omitempty"`
	Status        uint32                 `protobuf:"varint,5,opt,name=status,proto3" json:"status,omitempty" gorm:"type:int2;default:0"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TableColumn) Reset() {
	*x = TableColumn{}
	mi := &file_hopeio_model_table_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TableColumn) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TableColumn) ProtoMessage() {}

func (x *TableColumn) ProtoReflect() protoreflect.Message {
	mi := &file_hopeio_model_table_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TableColumn.ProtoReflect.Descriptor instead.
func (*TableColumn) Descriptor() ([]byte, []int) {
	return file_hopeio_model_table_proto_rawDescGZIP(), []int{1}
}

func (x *TableColumn) GetModel() *Model {
	if x != nil {
		return x.Model
	}
	return nil
}

func (x *TableColumn) GetTableId() uint64 {
	if x != nil {
		return x.TableId
	}
	return 0
}

func (x *TableColumn) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *TableColumn) GetType() uint32 {
	if x != nil {
		return x.Type
	}
	return 0
}

func (x *TableColumn) GetStatus() uint32 {
	if x != nil {
		return x.Status
	}
	return 0
}

type TableValue struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Model         *Model                 `protobuf:"bytes,1,opt,name=model,proto3" json:",inline" gorm:"embedded"`
	ColumnId      string                 `protobuf:"bytes,2,opt,name=columnId,proto3" json:"columnId,omitempty"`
	Value         string                 `protobuf:"bytes,3,opt,name=value,proto3" json:"value,omitempty" comment:"值"`
	Status        uint32                 `protobuf:"varint,18,opt,name=status,proto3" json:"status,omitempty" gorm:"type:int2;default:0"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TableValue) Reset() {
	*x = TableValue{}
	mi := &file_hopeio_model_table_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TableValue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TableValue) ProtoMessage() {}

func (x *TableValue) ProtoReflect() protoreflect.Message {
	mi := &file_hopeio_model_table_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TableValue.ProtoReflect.Descriptor instead.
func (*TableValue) Descriptor() ([]byte, []int) {
	return file_hopeio_model_table_proto_rawDescGZIP(), []int{2}
}

func (x *TableValue) GetModel() *Model {
	if x != nil {
		return x.Model
	}
	return nil
}

func (x *TableValue) GetColumnId() string {
	if x != nil {
		return x.ColumnId
	}
	return ""
}

func (x *TableValue) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *TableValue) GetStatus() uint32 {
	if x != nil {
		return x.Status
	}
	return 0
}

var File_hopeio_model_table_proto protoreflect.FileDescriptor

const file_hopeio_model_table_proto_rawDesc = "" +
	"\n" +
	"\x18hopeio/model/table.proto\x12\x05model\x1a\x1bhopeio/utils/patch/go.proto\x1a%hopeio/time/timestamp/timestamp.proto\x1a%hopeio/time/deletedAt/deletedAt.proto\x1a\x18hopeio/model/basic.proto\x1a.protoc-gen-openapiv2/options/annotations.proto\"\xc2\x01\n" +
	"\tTableMeta\x12I\n" +
	"\x05model\x18\x01 \x01(\v2\f.model.ModelB%ҵ\x03!\xa2\x01\x1ejson:\",inline\" gorm:\"embedded\"R\x05model\x12*\n" +
	"\x04name\x18\x02 \x01(\tB\x16ҵ\x03\x12\xa2\x01\x0fcomment:\"名称R\x04name\x12>\n" +
	"\x06status\x18\x03 \x01(\rB&\x92A\x02@\x01ҵ\x03\x1d\xa2\x01\x1agorm:\"type:int2;default:0\"R\x06status\"\xa9\x02\n" +
	"\vTableColumn\x12I\n" +
	"\x05model\x18\x01 \x01(\v2\f.model.ModelB%ҵ\x03!\xa2\x01\x1ejson:\",inline\" gorm:\"embedded\"R\x05model\x127\n" +
	"\atableId\x18\x02 \x01(\x04B\x1dҵ\x03\x19\xa2\x01\x16gorm:\"comment:tableId\"R\atableId\x12*\n" +
	"\x04name\x18\x03 \x01(\tB\x16ҵ\x03\x12\xa2\x01\x0fcomment:\"名称R\x04name\x12*\n" +
	"\x04type\x18\x04 \x01(\rB\x16ҵ\x03\x12\xa2\x01\x0fcomment:\"类型R\x04type\x12>\n" +
	"\x06status\x18\x05 \x01(\rB&\x92A\x02@\x01ҵ\x03\x1d\xa2\x01\x1agorm:\"type:int2;default:0\"R\x06status\"\xf7\x01\n" +
	"\n" +
	"TableValue\x12I\n" +
	"\x05model\x18\x01 \x01(\v2\f.model.ModelB%ҵ\x03!\xa2\x01\x1ejson:\",inline\" gorm:\"embedded\"R\x05model\x122\n" +
	"\bcolumnId\x18\x02 \x01(\tB\x16ҵ\x03\x12\xa2\x01\x0fcomment:\"名称R\bcolumnId\x12*\n" +
	"\x05value\x18\x03 \x01(\tB\x14ҵ\x03\x10\xa2\x01\rcomment:\"值\"R\x05value\x12>\n" +
	"\x06status\x18\x12 \x01(\rB&\x92A\x02@\x01ҵ\x03\x1d\xa2\x01\x1agorm:\"type:int2;default:0\"R\x06statusB>\n" +
	"\x18xyz.hoper.protobuf.modelP\x01Z github.com/hopeio/protobuf/modelb\x06proto3"

var (
	file_hopeio_model_table_proto_rawDescOnce sync.Once
	file_hopeio_model_table_proto_rawDescData []byte
)

func file_hopeio_model_table_proto_rawDescGZIP() []byte {
	file_hopeio_model_table_proto_rawDescOnce.Do(func() {
		file_hopeio_model_table_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_hopeio_model_table_proto_rawDesc), len(file_hopeio_model_table_proto_rawDesc)))
	})
	return file_hopeio_model_table_proto_rawDescData
}

var file_hopeio_model_table_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_hopeio_model_table_proto_goTypes = []any{
	(*TableMeta)(nil),   // 0: model.TableMeta
	(*TableColumn)(nil), // 1: model.TableColumn
	(*TableValue)(nil),  // 2: model.TableValue
	(*Model)(nil),       // 3: model.Model
}
var file_hopeio_model_table_proto_depIdxs = []int32{
	3, // 0: model.TableMeta.model:type_name -> model.Model
	3, // 1: model.TableColumn.model:type_name -> model.Model
	3, // 2: model.TableValue.model:type_name -> model.Model
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_hopeio_model_table_proto_init() }
func file_hopeio_model_table_proto_init() {
	if File_hopeio_model_table_proto != nil {
		return
	}
	file_hopeio_model_basic_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_hopeio_model_table_proto_rawDesc), len(file_hopeio_model_table_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_hopeio_model_table_proto_goTypes,
		DependencyIndexes: file_hopeio_model_table_proto_depIdxs,
		MessageInfos:      file_hopeio_model_table_proto_msgTypes,
	}.Build()
	File_hopeio_model_table_proto = out.File
	file_hopeio_model_table_proto_goTypes = nil
	file_hopeio_model_table_proto_depIdxs = nil
}
