//
// Copyright 2024 hopeio. All rights reserved.
// Licensed under the MIT License that can be found in the LICENSE file.
// @Created by jyb

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        v6.32.0
// source: hopeio/request/param.proto

package request

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Page struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PageNo        uint32                 `protobuf:"varint,1,opt,name=pageNo,proto3" json:"pageNo,omitempty"`
	PageSize      uint32                 `protobuf:"varint,2,opt,name=pageSize,proto3" json:"pageSize,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Page) Reset() {
	*x = Page{}
	mi := &file_hopeio_request_param_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Page) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Page) ProtoMessage() {}

func (x *Page) ProtoReflect() protoreflect.Message {
	mi := &file_hopeio_request_param_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Page.ProtoReflect.Descriptor instead.
func (*Page) Descriptor() ([]byte, []int) {
	return file_hopeio_request_param_proto_rawDescGZIP(), []int{0}
}

func (x *Page) GetPageNo() uint32 {
	if x != nil {
		return x.PageNo
	}
	return 0
}

func (x *Page) GetPageSize() uint32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type Id struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Id) Reset() {
	*x = Id{}
	mi := &file_hopeio_request_param_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Id) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Id) ProtoMessage() {}

func (x *Id) ProtoReflect() protoreflect.Message {
	mi := &file_hopeio_request_param_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Id.ProtoReflect.Descriptor instead.
func (*Id) Descriptor() ([]byte, []int) {
	return file_hopeio_request_param_proto_rawDescGZIP(), []int{1}
}

func (x *Id) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type IdStr struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IdStr         string                 `protobuf:"bytes,1,opt,name=idStr,proto3" json:"idStr,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IdStr) Reset() {
	*x = IdStr{}
	mi := &file_hopeio_request_param_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IdStr) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IdStr) ProtoMessage() {}

func (x *IdStr) ProtoReflect() protoreflect.Message {
	mi := &file_hopeio_request_param_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IdStr.ProtoReflect.Descriptor instead.
func (*IdStr) Descriptor() ([]byte, []int) {
	return file_hopeio_request_param_proto_rawDescGZIP(), []int{2}
}

func (x *IdStr) GetIdStr() string {
	if x != nil {
		return x.IdStr
	}
	return ""
}

type Cursor struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Cursor        uint64                 `protobuf:"varint,1,opt,name=cursor,proto3" json:"cursor,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Cursor) Reset() {
	*x = Cursor{}
	mi := &file_hopeio_request_param_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Cursor) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Cursor) ProtoMessage() {}

func (x *Cursor) ProtoReflect() protoreflect.Message {
	mi := &file_hopeio_request_param_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Cursor.ProtoReflect.Descriptor instead.
func (*Cursor) Descriptor() ([]byte, []int) {
	return file_hopeio_request_param_proto_rawDescGZIP(), []int{3}
}

func (x *Cursor) GetCursor() uint64 {
	if x != nil {
		return x.Cursor
	}
	return 0
}

type CursorStr struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Cursor        string                 `protobuf:"bytes,1,opt,name=cursor,proto3" json:"cursor,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CursorStr) Reset() {
	*x = CursorStr{}
	mi := &file_hopeio_request_param_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CursorStr) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CursorStr) ProtoMessage() {}

func (x *CursorStr) ProtoReflect() protoreflect.Message {
	mi := &file_hopeio_request_param_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CursorStr.ProtoReflect.Descriptor instead.
func (*CursorStr) Descriptor() ([]byte, []int) {
	return file_hopeio_request_param_proto_rawDescGZIP(), []int{4}
}

func (x *CursorStr) GetCursor() string {
	if x != nil {
		return x.Cursor
	}
	return ""
}

var File_hopeio_request_param_proto protoreflect.FileDescriptor

const file_hopeio_request_param_proto_rawDesc = "" +
	"\n" +
	"\x1ahopeio/request/param.proto\x12\arequest\":\n" +
	"\x04Page\x12\x16\n" +
	"\x06pageNo\x18\x01 \x01(\rR\x06pageNo\x12\x1a\n" +
	"\bpageSize\x18\x02 \x01(\rR\bpageSize\"\x14\n" +
	"\x02Id\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\"\x1d\n" +
	"\x05IdStr\x12\x14\n" +
	"\x05idStr\x18\x01 \x01(\tR\x05idStr\" \n" +
	"\x06Cursor\x12\x16\n" +
	"\x06cursor\x18\x01 \x01(\x04R\x06cursor\"#\n" +
	"\tCursorStr\x12\x16\n" +
	"\x06cursor\x18\x01 \x01(\tR\x06cursorBB\n" +
	"\x1axyz.hoper.protobuf.requestP\x01Z\"github.com/hopeio/protobuf/requestb\x06proto3"

var (
	file_hopeio_request_param_proto_rawDescOnce sync.Once
	file_hopeio_request_param_proto_rawDescData []byte
)

func file_hopeio_request_param_proto_rawDescGZIP() []byte {
	file_hopeio_request_param_proto_rawDescOnce.Do(func() {
		file_hopeio_request_param_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_hopeio_request_param_proto_rawDesc), len(file_hopeio_request_param_proto_rawDesc)))
	})
	return file_hopeio_request_param_proto_rawDescData
}

var file_hopeio_request_param_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_hopeio_request_param_proto_goTypes = []any{
	(*Page)(nil),      // 0: request.Page
	(*Id)(nil),        // 1: request.Id
	(*IdStr)(nil),     // 2: request.IdStr
	(*Cursor)(nil),    // 3: request.Cursor
	(*CursorStr)(nil), // 4: request.CursorStr
}
var file_hopeio_request_param_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_hopeio_request_param_proto_init() }
func file_hopeio_request_param_proto_init() {
	if File_hopeio_request_param_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_hopeio_request_param_proto_rawDesc), len(file_hopeio_request_param_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_hopeio_request_param_proto_goTypes,
		DependencyIndexes: file_hopeio_request_param_proto_depIdxs,
		MessageInfos:      file_hopeio_request_param_proto_msgTypes,
	}.Build()
	File_hopeio_request_param_proto = out.File
	file_hopeio_request_param_proto_goTypes = nil
	file_hopeio_request_param_proto_depIdxs = nil
}
