//
// Copyright 2024 hopeio. All rights reserved.
// Licensed under the MIT License that can be found in the LICENSE file.
// @Created by jyb

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        v6.32.0
// source: hopeio/model/enum/enum.proto

package enum

import (
	_ "github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-openapiv2/options"
	deletedAt "github.com/hopeio/protobuf/time/deletedAt"
	timestamp "github.com/hopeio/protobuf/time/timestamp"
	_ "github.com/hopeio/protobuf/utils/patch"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Enum struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty" gorm:"primaryKey"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Group         uint64                 `protobuf:"varint,3,opt,name=group,proto3" json:"group,omitempty" gorm:"size:20"`
	Type          uint32                 `protobuf:"varint,6,opt,name=type,proto3" json:"type,omitempty" comment:"类型"`
	CreatedAt     *timestamp.Timestamp   `protobuf:"bytes,16,opt,name=createdAt,proto3" json:"createdAt,omitempty" gorm:"type:timestamptz(6);default:now();index"`
	UpdatedAt     *timestamp.Timestamp   `protobuf:"bytes,26,opt,name=updatedAt,proto3" json:"updatedAt,omitempty" gorm:"type:timestamptz(6)"`
	DeletedAt     *deletedAt.DeletedAt   `protobuf:"bytes,28,opt,name=deletedAt,proto3" json:"deletedAt,omitempty" gorm:"<-:false;type:timestamptz(6);index"`
	Status        uint32                 `protobuf:"varint,18,opt,name=status,proto3" json:"status,omitempty" gorm:"type:int2;default:0"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Enum) Reset() {
	*x = Enum{}
	mi := &file_hopeio_model_enum_enum_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Enum) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Enum) ProtoMessage() {}

func (x *Enum) ProtoReflect() protoreflect.Message {
	mi := &file_hopeio_model_enum_enum_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Enum.ProtoReflect.Descriptor instead.
func (*Enum) Descriptor() ([]byte, []int) {
	return file_hopeio_model_enum_enum_proto_rawDescGZIP(), []int{0}
}

func (x *Enum) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Enum) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Enum) GetGroup() uint64 {
	if x != nil {
		return x.Group
	}
	return 0
}

func (x *Enum) GetType() uint32 {
	if x != nil {
		return x.Type
	}
	return 0
}

func (x *Enum) GetCreatedAt() *timestamp.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Enum) GetUpdatedAt() *timestamp.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *Enum) GetDeletedAt() *deletedAt.DeletedAt {
	if x != nil {
		return x.DeletedAt
	}
	return nil
}

func (x *Enum) GetStatus() uint32 {
	if x != nil {
		return x.Status
	}
	return 0
}

type EnumValue struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty" gorm:"primaryKey"`
	EnumId        uint64                 `protobuf:"varint,2,opt,name=enumId,proto3" json:"enumId,omitempty"`
	Index         uint64                 `protobuf:"varint,3,opt,name=index,proto3" json:"index,omitempty" gorm:"comment:index"`
	Value         string                 `protobuf:"bytes,5,opt,name=value,proto3" json:"value,omitempty" comment:"值"`
	CreatedAt     *timestamp.Timestamp   `protobuf:"bytes,16,opt,name=createdAt,proto3" json:"createdAt,omitempty" gorm:"type:timestamptz(6);default:now();index"`
	UpdatedAt     *timestamp.Timestamp   `protobuf:"bytes,26,opt,name=updatedAt,proto3" json:"updatedAt,omitempty" gorm:"type:timestamptz(6)"`
	DeletedAt     *deletedAt.DeletedAt   `protobuf:"bytes,28,opt,name=deletedAt,proto3" json:"deletedAt,omitempty" gorm:"<-:false;type:timestamptz(6);index"`
	Status        uint32                 `protobuf:"varint,18,opt,name=status,proto3" json:"status,omitempty" gorm:"type:int2;default:0"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnumValue) Reset() {
	*x = EnumValue{}
	mi := &file_hopeio_model_enum_enum_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnumValue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnumValue) ProtoMessage() {}

func (x *EnumValue) ProtoReflect() protoreflect.Message {
	mi := &file_hopeio_model_enum_enum_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnumValue.ProtoReflect.Descriptor instead.
func (*EnumValue) Descriptor() ([]byte, []int) {
	return file_hopeio_model_enum_enum_proto_rawDescGZIP(), []int{1}
}

func (x *EnumValue) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *EnumValue) GetEnumId() uint64 {
	if x != nil {
		return x.EnumId
	}
	return 0
}

func (x *EnumValue) GetIndex() uint64 {
	if x != nil {
		return x.Index
	}
	return 0
}

func (x *EnumValue) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *EnumValue) GetCreatedAt() *timestamp.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *EnumValue) GetUpdatedAt() *timestamp.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *EnumValue) GetDeletedAt() *deletedAt.DeletedAt {
	if x != nil {
		return x.DeletedAt
	}
	return nil
}

func (x *EnumValue) GetStatus() uint32 {
	if x != nil {
		return x.Status
	}
	return 0
}

var File_hopeio_model_enum_enum_proto protoreflect.FileDescriptor

const file_hopeio_model_enum_enum_proto_rawDesc = "" +
	"\n" +
	"\x1chopeio/model/enum/enum.proto\x12\x04enum\x1a\x1bhopeio/utils/patch/go.proto\x1a%hopeio/time/timestamp/timestamp.proto\x1a%hopeio/time/deletedAt/deletedAt.proto\x1a.protoc-gen-openapiv2/options/annotations.proto\"\x9e\x04\n" +
	"\x04Enum\x12(\n" +
	"\x02id\x18\x01 \x01(\x04B\x18ҵ\x03\x14\xa2\x01\x11gorm:\"primaryKey\"R\x02id\x12*\n" +
	"\x04name\x18\x02 \x01(\tB\x16ҵ\x03\x12\xa2\x01\x0fcomment:\"名称R\x04name\x12+\n" +
	"\x05group\x18\x03 \x01(\x04B\x15ҵ\x03\x11\xa2\x01\x0egorm:\"size:20\"R\x05group\x12+\n" +
	"\x04type\x18\x06 \x01(\rB\x17ҵ\x03\x13\xa2\x01\x10comment:\"类型\"R\x04type\x12i\n" +
	"\tcreatedAt\x18\x10 \x01(\v2\x14.timestamp.TimestampB5ҵ\x031\xa2\x01.gorm:\"type:timestamptz(6);default:now();index\"R\tcreatedAt\x12U\n" +
	"\tupdatedAt\x18\x1a \x01(\v2\x14.timestamp.TimestampB!ҵ\x03\x1d\xa2\x01\x1agorm:\"type:timestamptz(6)\"R\tupdatedAt\x12d\n" +
	"\tdeletedAt\x18\x1c \x01(\v2\x14.deletedAt.DeletedAtB0ҵ\x03,\xa2\x01)gorm:\"<-:false;type:timestamptz(6);index\"R\tdeletedAt\x12>\n" +
	"\x06status\x18\x12 \x01(\rB&\x92A\x02@\x01ҵ\x03\x1d\xa2\x01\x1agorm:\"type:int2;default:0\"R\x06status\"\xae\x04\n" +
	"\tEnumValue\x12(\n" +
	"\x02id\x18\x01 \x01(\x04B\x18ҵ\x03\x14\xa2\x01\x11gorm:\"primaryKey\"R\x02id\x120\n" +
	"\x06enumId\x18\x02 \x01(\x04B\x18ҵ\x03\x14\xa2\x01\x11comment:\"枚举idR\x06enumId\x121\n" +
	"\x05index\x18\x03 \x01(\x04B\x1bҵ\x03\x17\xa2\x01\x14gorm:\"comment:index\"R\x05index\x12*\n" +
	"\x05value\x18\x05 \x01(\tB\x14ҵ\x03\x10\xa2\x01\rcomment:\"值\"R\x05value\x12i\n" +
	"\tcreatedAt\x18\x10 \x01(\v2\x14.timestamp.TimestampB5ҵ\x031\xa2\x01.gorm:\"type:timestamptz(6);default:now();index\"R\tcreatedAt\x12U\n" +
	"\tupdatedAt\x18\x1a \x01(\v2\x14.timestamp.TimestampB!ҵ\x03\x1d\xa2\x01\x1agorm:\"type:timestamptz(6)\"R\tupdatedAt\x12d\n" +
	"\tdeletedAt\x18\x1c \x01(\v2\x14.deletedAt.DeletedAtB0ҵ\x03,\xa2\x01)gorm:\"<-:false;type:timestamptz(6);index\"R\tdeletedAt\x12>\n" +
	"\x06status\x18\x12 \x01(\rB&\x92A\x02@\x01ҵ\x03\x1d\xa2\x01\x1agorm:\"type:int2;default:0\"R\x06statusBJ\n" +
	"\x1fxyz.hoper.protobuf.model.enumpbP\x01Z%github.com/hopeio/protobuf/model/enumb\x06proto3"

var (
	file_hopeio_model_enum_enum_proto_rawDescOnce sync.Once
	file_hopeio_model_enum_enum_proto_rawDescData []byte
)

func file_hopeio_model_enum_enum_proto_rawDescGZIP() []byte {
	file_hopeio_model_enum_enum_proto_rawDescOnce.Do(func() {
		file_hopeio_model_enum_enum_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_hopeio_model_enum_enum_proto_rawDesc), len(file_hopeio_model_enum_enum_proto_rawDesc)))
	})
	return file_hopeio_model_enum_enum_proto_rawDescData
}

var file_hopeio_model_enum_enum_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_hopeio_model_enum_enum_proto_goTypes = []any{
	(*Enum)(nil),                // 0: enum.Enum
	(*EnumValue)(nil),           // 1: enum.EnumValue
	(*timestamp.Timestamp)(nil), // 2: timestamp.Timestamp
	(*deletedAt.DeletedAt)(nil), // 3: deletedAt.DeletedAt
}
var file_hopeio_model_enum_enum_proto_depIdxs = []int32{
	2, // 0: enum.Enum.createdAt:type_name -> timestamp.Timestamp
	2, // 1: enum.Enum.updatedAt:type_name -> timestamp.Timestamp
	3, // 2: enum.Enum.deletedAt:type_name -> deletedAt.DeletedAt
	2, // 3: enum.EnumValue.createdAt:type_name -> timestamp.Timestamp
	2, // 4: enum.EnumValue.updatedAt:type_name -> timestamp.Timestamp
	3, // 5: enum.EnumValue.deletedAt:type_name -> deletedAt.DeletedAt
	6, // [6:6] is the sub-list for method output_type
	6, // [6:6] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_hopeio_model_enum_enum_proto_init() }
func file_hopeio_model_enum_enum_proto_init() {
	if File_hopeio_model_enum_enum_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_hopeio_model_enum_enum_proto_rawDesc), len(file_hopeio_model_enum_enum_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_hopeio_model_enum_enum_proto_goTypes,
		DependencyIndexes: file_hopeio_model_enum_enum_proto_depIdxs,
		MessageInfos:      file_hopeio_model_enum_enum_proto_msgTypes,
	}.Build()
	File_hopeio_model_enum_enum_proto = out.File
	file_hopeio_model_enum_enum_proto_goTypes = nil
	file_hopeio_model_enum_enum_proto_depIdxs = nil
}
