//
// Copyright 2024 hopeio. All rights reserved.
// Licensed under the MIT License that can be found in the LICENSE file.
// @Created by jyb

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        v6.32.0
// source: hopeio/model/area/area.proto

package area

import (
	_ "github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-openapiv2/options"
	deletedAt "github.com/hopeio/protobuf/time/deletedAt"
	timestamp "github.com/hopeio/protobuf/time/timestamp"
	_ "github.com/hopeio/protobuf/utils/patch"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Area struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          uint64                 `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty" gorm:"primaryKey"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Level         int32                  `protobuf:"varint,3,opt,name=level,proto3" json:"level,omitempty"`
	Pcode         uint64                 `protobuf:"varint,4,opt,name=pcode,proto3" json:"pcode,omitempty"`
	CreatedAt     *timestamp.Timestamp   `protobuf:"bytes,16,opt,name=createdAt,proto3" json:"createdAt,omitempty" gorm:"type:timestamptz(6);default:now();index"`
	UpdatedAt     *timestamp.Timestamp   `protobuf:"bytes,26,opt,name=updatedAt,proto3" json:"updatedAt,omitempty" gorm:"type:timestamptz(6)"`
	DeletedAt     *deletedAt.DeletedAt   `protobuf:"bytes,28,opt,name=deletedAt,proto3" json:"deletedAt,omitempty" gorm:"<-:false;type:timestamptz(6);index"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Area) Reset() {
	*x = Area{}
	mi := &file_hopeio_model_area_area_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Area) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Area) ProtoMessage() {}

func (x *Area) ProtoReflect() protoreflect.Message {
	mi := &file_hopeio_model_area_area_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Area.ProtoReflect.Descriptor instead.
func (*Area) Descriptor() ([]byte, []int) {
	return file_hopeio_model_area_area_proto_rawDescGZIP(), []int{0}
}

func (x *Area) GetCode() uint64 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *Area) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Area) GetLevel() int32 {
	if x != nil {
		return x.Level
	}
	return 0
}

func (x *Area) GetPcode() uint64 {
	if x != nil {
		return x.Pcode
	}
	return 0
}

func (x *Area) GetCreatedAt() *timestamp.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Area) GetUpdatedAt() *timestamp.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *Area) GetDeletedAt() *deletedAt.DeletedAt {
	if x != nil {
		return x.DeletedAt
	}
	return nil
}

var File_hopeio_model_area_area_proto protoreflect.FileDescriptor

const file_hopeio_model_area_area_proto_rawDesc = "" +
	"\n" +
	"\x1chopeio/model/area/area.proto\x12\x04area\x1a\x1bhopeio/utils/patch/go.proto\x1a%hopeio/time/timestamp/timestamp.proto\x1a%hopeio/time/deletedAt/deletedAt.proto\x1a.protoc-gen-openapiv2/options/annotations.proto\"\x9c\x03\n" +
	"\x04Area\x12,\n" +
	"\x04code\x18\x01 \x01(\x04B\x18ҵ\x03\x14\xa2\x01\x11gorm:\"primaryKey\"R\x04code\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x14\n" +
	"\x05level\x18\x03 \x01(\x05R\x05level\x12\x14\n" +
	"\x05pcode\x18\x04 \x01(\x04R\x05pcode\x12i\n" +
	"\tcreatedAt\x18\x10 \x01(\v2\x14.timestamp.TimestampB5ҵ\x031\xa2\x01.gorm:\"type:timestamptz(6);default:now();index\"R\tcreatedAt\x12U\n" +
	"\tupdatedAt\x18\x1a \x01(\v2\x14.timestamp.TimestampB!ҵ\x03\x1d\xa2\x01\x1agorm:\"type:timestamptz(6)\"R\tupdatedAt\x12d\n" +
	"\tdeletedAt\x18\x1c \x01(\v2\x14.deletedAt.DeletedAtB0ҵ\x03,\xa2\x01)gorm:\"<-:false;type:timestamptz(6);index\"R\tdeletedAtBH\n" +
	"\x1dxyz.hoper.protobuf.model.areaP\x01Z%github.com/hopeio/protobuf/model/areab\x06proto3"

var (
	file_hopeio_model_area_area_proto_rawDescOnce sync.Once
	file_hopeio_model_area_area_proto_rawDescData []byte
)

func file_hopeio_model_area_area_proto_rawDescGZIP() []byte {
	file_hopeio_model_area_area_proto_rawDescOnce.Do(func() {
		file_hopeio_model_area_area_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_hopeio_model_area_area_proto_rawDesc), len(file_hopeio_model_area_area_proto_rawDesc)))
	})
	return file_hopeio_model_area_area_proto_rawDescData
}

var file_hopeio_model_area_area_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_hopeio_model_area_area_proto_goTypes = []any{
	(*Area)(nil),                // 0: area.Area
	(*timestamp.Timestamp)(nil), // 1: timestamp.Timestamp
	(*deletedAt.DeletedAt)(nil), // 2: deletedAt.DeletedAt
}
var file_hopeio_model_area_area_proto_depIdxs = []int32{
	1, // 0: area.Area.createdAt:type_name -> timestamp.Timestamp
	1, // 1: area.Area.updatedAt:type_name -> timestamp.Timestamp
	2, // 2: area.Area.deletedAt:type_name -> deletedAt.DeletedAt
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_hopeio_model_area_area_proto_init() }
func file_hopeio_model_area_area_proto_init() {
	if File_hopeio_model_area_area_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_hopeio_model_area_area_proto_rawDesc), len(file_hopeio_model_area_area_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_hopeio_model_area_area_proto_goTypes,
		DependencyIndexes: file_hopeio_model_area_area_proto_depIdxs,
		MessageInfos:      file_hopeio_model_area_area_proto_msgTypes,
	}.Build()
	File_hopeio_model_area_area_proto = out.File
	file_hopeio_model_area_area_proto_goTypes = nil
	file_hopeio_model_area_area_proto_depIdxs = nil
}
