//
// Copyright 2024 hopeio. All rights reserved.
// Licensed under the MIT License that can be found in the LICENSE file.
// @Created by jyb

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.32.0
// source: hopeio/model/table/table.proto

package table

import (
	_ "github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-openapiv2/options"
	deletedAt "github.com/hopeio/protobuf/time/deletedAt"
	timestamp "github.com/hopeio/protobuf/time/timestamp"
	_ "github.com/hopeio/protobuf/utils/patch"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TableMeta struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty" gorm:"primaryKey"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	CreatedAt     *timestamp.Timestamp   `protobuf:"bytes,16,opt,name=createdAt,proto3" json:"createdAt,omitempty" gorm:"type:timestamptz(6);default:now();index"`
	UpdatedAt     *timestamp.Timestamp   `protobuf:"bytes,26,opt,name=updatedAt,proto3" json:"updatedAt,omitempty" gorm:"type:timestamptz(6)"`
	DeletedAt     *deletedAt.DeletedAt   `protobuf:"bytes,28,opt,name=deletedAt,proto3" json:"deletedAt,omitempty" gorm:"<-:false;type:timestamptz(6);index"`
	Status        uint32                 `protobuf:"varint,18,opt,name=status,proto3" json:"status,omitempty" gorm:"type:int2;default:0"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TableMeta) Reset() {
	*x = TableMeta{}
	mi := &file_hopeio_model_table_table_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TableMeta) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TableMeta) ProtoMessage() {}

func (x *TableMeta) ProtoReflect() protoreflect.Message {
	mi := &file_hopeio_model_table_table_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TableMeta.ProtoReflect.Descriptor instead.
func (*TableMeta) Descriptor() ([]byte, []int) {
	return file_hopeio_model_table_table_proto_rawDescGZIP(), []int{0}
}

func (x *TableMeta) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *TableMeta) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *TableMeta) GetCreatedAt() *timestamp.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *TableMeta) GetUpdatedAt() *timestamp.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *TableMeta) GetDeletedAt() *deletedAt.DeletedAt {
	if x != nil {
		return x.DeletedAt
	}
	return nil
}

func (x *TableMeta) GetStatus() uint32 {
	if x != nil {
		return x.Status
	}
	return 0
}

type TableColumn struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty" gorm:"primaryKey"`
	TableId       uint64                 `protobuf:"varint,2,opt,name=tableId,proto3" json:"tableId,omitempty" gorm:"comment:tableId"`
	Name          string                 `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	Type          uint32                 `protobuf:"varint,5,opt,name=type,proto3" json:"type,omitempty"`
	CreatedAt     *timestamp.Timestamp   `protobuf:"bytes,16,opt,name=createdAt,proto3" json:"createdAt,omitempty" gorm:"type:timestamptz(6);default:now();index"`
	UpdatedAt     *timestamp.Timestamp   `protobuf:"bytes,26,opt,name=updatedAt,proto3" json:"updatedAt,omitempty" gorm:"type:timestamptz(6)"`
	DeletedAt     *deletedAt.DeletedAt   `protobuf:"bytes,28,opt,name=deletedAt,proto3" json:"deletedAt,omitempty" gorm:"<-:false;type:timestamptz(6);index"`
	Status        uint32                 `protobuf:"varint,18,opt,name=status,proto3" json:"status,omitempty" gorm:"type:int2;default:0"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TableColumn) Reset() {
	*x = TableColumn{}
	mi := &file_hopeio_model_table_table_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TableColumn) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TableColumn) ProtoMessage() {}

func (x *TableColumn) ProtoReflect() protoreflect.Message {
	mi := &file_hopeio_model_table_table_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TableColumn.ProtoReflect.Descriptor instead.
func (*TableColumn) Descriptor() ([]byte, []int) {
	return file_hopeio_model_table_table_proto_rawDescGZIP(), []int{1}
}

func (x *TableColumn) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *TableColumn) GetTableId() uint64 {
	if x != nil {
		return x.TableId
	}
	return 0
}

func (x *TableColumn) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *TableColumn) GetType() uint32 {
	if x != nil {
		return x.Type
	}
	return 0
}

func (x *TableColumn) GetCreatedAt() *timestamp.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *TableColumn) GetUpdatedAt() *timestamp.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *TableColumn) GetDeletedAt() *deletedAt.DeletedAt {
	if x != nil {
		return x.DeletedAt
	}
	return nil
}

func (x *TableColumn) GetStatus() uint32 {
	if x != nil {
		return x.Status
	}
	return 0
}

type TableValue struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty" gorm:"primaryKey"`
	ColumnId      string                 `protobuf:"bytes,2,opt,name=columnId,proto3" json:"columnId,omitempty"`
	Value         string                 `protobuf:"bytes,3,opt,name=value,proto3" json:"value,omitempty" comment:"值"`
	CreatedAt     *timestamp.Timestamp   `protobuf:"bytes,16,opt,name=createdAt,proto3" json:"createdAt,omitempty" gorm:"type:timestamptz(6);default:now();index"`
	UpdatedAt     *timestamp.Timestamp   `protobuf:"bytes,26,opt,name=updatedAt,proto3" json:"updatedAt,omitempty" gorm:"type:timestamptz(6)"`
	DeletedAt     *deletedAt.DeletedAt   `protobuf:"bytes,28,opt,name=deletedAt,proto3" json:"deletedAt,omitempty" gorm:"<-:false;type:timestamptz(6);index"`
	Status        uint32                 `protobuf:"varint,18,opt,name=status,proto3" json:"status,omitempty" gorm:"type:int2;default:0"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TableValue) Reset() {
	*x = TableValue{}
	mi := &file_hopeio_model_table_table_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TableValue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TableValue) ProtoMessage() {}

func (x *TableValue) ProtoReflect() protoreflect.Message {
	mi := &file_hopeio_model_table_table_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TableValue.ProtoReflect.Descriptor instead.
func (*TableValue) Descriptor() ([]byte, []int) {
	return file_hopeio_model_table_table_proto_rawDescGZIP(), []int{2}
}

func (x *TableValue) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *TableValue) GetColumnId() string {
	if x != nil {
		return x.ColumnId
	}
	return ""
}

func (x *TableValue) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *TableValue) GetCreatedAt() *timestamp.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *TableValue) GetUpdatedAt() *timestamp.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *TableValue) GetDeletedAt() *deletedAt.DeletedAt {
	if x != nil {
		return x.DeletedAt
	}
	return nil
}

func (x *TableValue) GetStatus() uint32 {
	if x != nil {
		return x.Status
	}
	return 0
}

var File_hopeio_model_table_table_proto protoreflect.FileDescriptor

const file_hopeio_model_table_table_proto_rawDesc = "" +
	"\n" +
	"\x1ehopeio/model/table/table.proto\x12\x05table\x1a\x1bhopeio/utils/patch/go.proto\x1a%hopeio/time/timestamp/timestamp.proto\x1a%hopeio/time/deletedAt/deletedAt.proto\x1a.protoc-gen-openapiv2/options/annotations.proto\"\xc9\x03\n" +
	"\tTableMeta\x12(\n" +
	"\x02id\x18\x01 \x01(\x04B\x18ҵ\x03\x14\xa2\x01\x11gorm:\"primaryKey\"R\x02id\x12*\n" +
	"\x04name\x18\x02 \x01(\tB\x16ҵ\x03\x12\xa2\x01\x0fcomment:\"名称R\x04name\x12i\n" +
	"\tcreatedAt\x18\x10 \x01(\v2\x14.timestamp.TimestampB5ҵ\x031\xa2\x01.gorm:\"type:timestamptz(6);default:now();index\"R\tcreatedAt\x12U\n" +
	"\tupdatedAt\x18\x1a \x01(\v2\x14.timestamp.TimestampB!ҵ\x03\x1d\xa2\x01\x1agorm:\"type:timestamptz(6)\"R\tupdatedAt\x12d\n" +
	"\tdeletedAt\x18\x1c \x01(\v2\x14.deletedAt.DeletedAtB0ҵ\x03,\xa2\x01)gorm:\"<-:false;type:timestamptz(6);index\"R\tdeletedAt\x12>\n" +
	"\x06status\x18\x12 \x01(\rB&\x92A\x02@\x01ҵ\x03\x1d\xa2\x01\x1agorm:\"type:int2;default:0\"R\x06status\"\xb0\x04\n" +
	"\vTableColumn\x12(\n" +
	"\x02id\x18\x01 \x01(\x04B\x18ҵ\x03\x14\xa2\x01\x11gorm:\"primaryKey\"R\x02id\x127\n" +
	"\atableId\x18\x02 \x01(\x04B\x1dҵ\x03\x19\xa2\x01\x16gorm:\"comment:tableId\"R\atableId\x12*\n" +
	"\x04name\x18\x04 \x01(\tB\x16ҵ\x03\x12\xa2\x01\x0fcomment:\"名称R\x04name\x12*\n" +
	"\x04type\x18\x05 \x01(\rB\x16ҵ\x03\x12\xa2\x01\x0fcomment:\"类型R\x04type\x12i\n" +
	"\tcreatedAt\x18\x10 \x01(\v2\x14.timestamp.TimestampB5ҵ\x031\xa2\x01.gorm:\"type:timestamptz(6);default:now();index\"R\tcreatedAt\x12U\n" +
	"\tupdatedAt\x18\x1a \x01(\v2\x14.timestamp.TimestampB!ҵ\x03\x1d\xa2\x01\x1agorm:\"type:timestamptz(6)\"R\tupdatedAt\x12d\n" +
	"\tdeletedAt\x18\x1c \x01(\v2\x14.deletedAt.DeletedAtB0ҵ\x03,\xa2\x01)gorm:\"<-:false;type:timestamptz(6);index\"R\tdeletedAt\x12>\n" +
	"\x06status\x18\x12 \x01(\rB&\x92A\x02@\x01ҵ\x03\x1d\xa2\x01\x1agorm:\"type:int2;default:0\"R\x06status\"\xfe\x03\n" +
	"\n" +
	"TableValue\x12(\n" +
	"\x02id\x18\x01 \x01(\x04B\x18ҵ\x03\x14\xa2\x01\x11gorm:\"primaryKey\"R\x02id\x122\n" +
	"\bcolumnId\x18\x02 \x01(\tB\x16ҵ\x03\x12\xa2\x01\x0fcomment:\"名称R\bcolumnId\x12*\n" +
	"\x05value\x18\x03 \x01(\tB\x14ҵ\x03\x10\xa2\x01\rcomment:\"值\"R\x05value\x12i\n" +
	"\tcreatedAt\x18\x10 \x01(\v2\x14.timestamp.TimestampB5ҵ\x031\xa2\x01.gorm:\"type:timestamptz(6);default:now();index\"R\tcreatedAt\x12U\n" +
	"\tupdatedAt\x18\x1a \x01(\v2\x14.timestamp.TimestampB!ҵ\x03\x1d\xa2\x01\x1agorm:\"type:timestamptz(6)\"R\tupdatedAt\x12d\n" +
	"\tdeletedAt\x18\x1c \x01(\v2\x14.deletedAt.DeletedAtB0ҵ\x03,\xa2\x01)gorm:\"<-:false;type:timestamptz(6);index\"R\tdeletedAt\x12>\n" +
	"\x06status\x18\x12 \x01(\rB&\x92A\x02@\x01ҵ\x03\x1d\xa2\x01\x1agorm:\"type:int2;default:0\"R\x06statusBJ\n" +
	"\x1exyz.hoper.protobuf.model.tableP\x01Z&github.com/hopeio/protobuf/model/tableb\x06proto3"

var (
	file_hopeio_model_table_table_proto_rawDescOnce sync.Once
	file_hopeio_model_table_table_proto_rawDescData []byte
)

func file_hopeio_model_table_table_proto_rawDescGZIP() []byte {
	file_hopeio_model_table_table_proto_rawDescOnce.Do(func() {
		file_hopeio_model_table_table_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_hopeio_model_table_table_proto_rawDesc), len(file_hopeio_model_table_table_proto_rawDesc)))
	})
	return file_hopeio_model_table_table_proto_rawDescData
}

var file_hopeio_model_table_table_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_hopeio_model_table_table_proto_goTypes = []any{
	(*TableMeta)(nil),           // 0: table.TableMeta
	(*TableColumn)(nil),         // 1: table.TableColumn
	(*TableValue)(nil),          // 2: table.TableValue
	(*timestamp.Timestamp)(nil), // 3: timestamp.Timestamp
	(*deletedAt.DeletedAt)(nil), // 4: deletedAt.DeletedAt
}
var file_hopeio_model_table_table_proto_depIdxs = []int32{
	3, // 0: table.TableMeta.createdAt:type_name -> timestamp.Timestamp
	3, // 1: table.TableMeta.updatedAt:type_name -> timestamp.Timestamp
	4, // 2: table.TableMeta.deletedAt:type_name -> deletedAt.DeletedAt
	3, // 3: table.TableColumn.createdAt:type_name -> timestamp.Timestamp
	3, // 4: table.TableColumn.updatedAt:type_name -> timestamp.Timestamp
	4, // 5: table.TableColumn.deletedAt:type_name -> deletedAt.DeletedAt
	3, // 6: table.TableValue.createdAt:type_name -> timestamp.Timestamp
	3, // 7: table.TableValue.updatedAt:type_name -> timestamp.Timestamp
	4, // 8: table.TableValue.deletedAt:type_name -> deletedAt.DeletedAt
	9, // [9:9] is the sub-list for method output_type
	9, // [9:9] is the sub-list for method input_type
	9, // [9:9] is the sub-list for extension type_name
	9, // [9:9] is the sub-list for extension extendee
	0, // [0:9] is the sub-list for field type_name
}

func init() { file_hopeio_model_table_table_proto_init() }
func file_hopeio_model_table_table_proto_init() {
	if File_hopeio_model_table_table_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_hopeio_model_table_table_proto_rawDesc), len(file_hopeio_model_table_table_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_hopeio_model_table_table_proto_goTypes,
		DependencyIndexes: file_hopeio_model_table_table_proto_depIdxs,
		MessageInfos:      file_hopeio_model_table_table_proto_msgTypes,
	}.Build()
	File_hopeio_model_table_table_proto = out.File
	file_hopeio_model_table_table_proto_goTypes = nil
	file_hopeio_model_table_table_proto_depIdxs = nil
}
