// Code generated by protoc-gen-gateway. DO NOT EDIT.
// source: stream.proto

/*
Package stream_test is a reverse proxy.

It translates gRPC into RESTful JSON APIs.
*/
package stream_test

import (
	"github.com/gin-gonic/gin"
	gateway "github.com/hopeio/mix/contrib/gin"
)

// RegisterDemoServiceHandlerServer registers the http handlers for service DemoService to "mux".
// UnaryRPC        : call DemoServiceServer directly.
// ServerStreaming : HTTP/2 chunked with gRPC length-prefixed JSON frames.
// ClientStreaming : read gRPC length-prefixed JSON frames from request body.
// BidiStreaming   : bidirectional gRPC length-prefixed frames.
func RegisterDemoServiceHandlerServer(mux *gin.Engine, server DemoServiceServer) {

	mux.Handle("GET", "/api/v1/ping", gateway.UnaryCall(server.Ping))

	mux.Handle("GET", "/api/v1/search", gateway.ServerSideStreamCall(server.Search))

	mux.Handle("POST", "/api/v1/upload", gateway.ClientSideStreamCall(server.Upload))

	mux.Handle("POST", "/api/v1/chat", gateway.BidiStreamCall(server.Chat))

}
