// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v6.33.1
// source: stream.proto

package stream_test

import (
	context "context"

	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	DemoService_Ping_FullMethodName   = "/stream_test.DemoService/Ping"
	DemoService_Search_FullMethodName = "/stream_test.DemoService/Search"
	DemoService_Upload_FullMethodName = "/stream_test.DemoService/Upload"
	DemoService_Chat_FullMethodName   = "/stream_test.DemoService/Chat"
)

// DemoServiceClient is the client API for DemoService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type DemoServiceClient interface {
	// unary
	Ping(ctx context.Context, in *PingRequest, opts ...grpc.CallOption) (*PongResponse, error)
	// server streaming — 核心测试场景
	Search(ctx context.Context, in *SearchRequest, opts ...grpc.CallOption) (DemoService_SearchClient, error)
	// client streaming —
	Upload(ctx context.Context, opts ...grpc.CallOption) (DemoService_UploadClient, error)
	// bidirectional streaming —
	Chat(ctx context.Context, opts ...grpc.CallOption) (DemoService_ChatClient, error)
}

type demoServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewDemoServiceClient(cc grpc.ClientConnInterface) DemoServiceClient {
	return &demoServiceClient{cc}
}

func (c *demoServiceClient) Ping(ctx context.Context, in *PingRequest, opts ...grpc.CallOption) (*PongResponse, error) {
	out := new(PongResponse)
	err := c.cc.Invoke(ctx, DemoService_Ping_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *demoServiceClient) Search(ctx context.Context, in *SearchRequest, opts ...grpc.CallOption) (DemoService_SearchClient, error) {
	stream, err := c.cc.NewStream(ctx, &DemoService_ServiceDesc.Streams[0], DemoService_Search_FullMethodName, opts...)
	if err != nil {
		return nil, err
	}
	x := &demoServiceSearchClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type DemoService_SearchClient interface {
	Recv() (*SearchResult, error)
	grpc.ClientStream
}

type demoServiceSearchClient struct {
	grpc.ClientStream
}

func (x *demoServiceSearchClient) Recv() (*SearchResult, error) {
	m := new(SearchResult)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *demoServiceClient) Upload(ctx context.Context, opts ...grpc.CallOption) (DemoService_UploadClient, error) {
	stream, err := c.cc.NewStream(ctx, &DemoService_ServiceDesc.Streams[1], DemoService_Upload_FullMethodName, opts...)
	if err != nil {
		return nil, err
	}
	x := &demoServiceUploadClient{stream}
	return x, nil
}

type DemoService_UploadClient interface {
	Send(*PingRequest) error
	CloseAndRecv() (*PongResponse, error)
	grpc.ClientStream
}

type demoServiceUploadClient struct {
	grpc.ClientStream
}

func (x *demoServiceUploadClient) Send(m *PingRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *demoServiceUploadClient) CloseAndRecv() (*PongResponse, error) {
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	m := new(PongResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *demoServiceClient) Chat(ctx context.Context, opts ...grpc.CallOption) (DemoService_ChatClient, error) {
	stream, err := c.cc.NewStream(ctx, &DemoService_ServiceDesc.Streams[2], DemoService_Chat_FullMethodName, opts...)
	if err != nil {
		return nil, err
	}
	x := &demoServiceChatClient{stream}
	return x, nil
}

type DemoService_ChatClient interface {
	Send(*PingRequest) error
	Recv() (*PongResponse, error)
	grpc.ClientStream
}

type demoServiceChatClient struct {
	grpc.ClientStream
}

func (x *demoServiceChatClient) Send(m *PingRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *demoServiceChatClient) Recv() (*PongResponse, error) {
	m := new(PongResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// DemoServiceServer is the server API for DemoService service.
// All implementations must embed UnimplementedDemoServiceServer
// for forward compatibility
type DemoServiceServer interface {
	// unary
	Ping(context.Context, *PingRequest) (*PongResponse, error)
	// server streaming — 核心测试场景
	Search(*SearchRequest, DemoService_SearchServer) error
	// client streaming —
	Upload(DemoService_UploadServer) error
	// bidirectional streaming —
	Chat(DemoService_ChatServer) error
	mustEmbedUnimplementedDemoServiceServer()
}

// UnimplementedDemoServiceServer must be embedded to have forward compatible implementations.
type UnimplementedDemoServiceServer struct {
}

func (UnimplementedDemoServiceServer) Ping(context.Context, *PingRequest) (*PongResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Ping not implemented")
}
func (UnimplementedDemoServiceServer) Search(*SearchRequest, DemoService_SearchServer) error {
	return status.Errorf(codes.Unimplemented, "method Search not implemented")
}
func (UnimplementedDemoServiceServer) Upload(DemoService_UploadServer) error {
	return status.Errorf(codes.Unimplemented, "method Upload not implemented")
}
func (UnimplementedDemoServiceServer) Chat(DemoService_ChatServer) error {
	return status.Errorf(codes.Unimplemented, "method Chat not implemented")
}
func (UnimplementedDemoServiceServer) mustEmbedUnimplementedDemoServiceServer() {}

// UnsafeDemoServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DemoServiceServer will
// result in compilation errors.
type UnsafeDemoServiceServer interface {
	mustEmbedUnimplementedDemoServiceServer()
}

func RegisterDemoServiceServer(s grpc.ServiceRegistrar, srv DemoServiceServer) {
	s.RegisterService(&DemoService_ServiceDesc, srv)
}

func _DemoService_Ping_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DemoServiceServer).Ping(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DemoService_Ping_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DemoServiceServer).Ping(ctx, req.(*PingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DemoService_Search_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(SearchRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(DemoServiceServer).Search(m, &demoServiceSearchServer{stream})
}

type DemoService_SearchServer interface {
	Send(*SearchResult) error
	grpc.ServerStream
}

type demoServiceSearchServer struct {
	grpc.ServerStream
}

func (x *demoServiceSearchServer) Send(m *SearchResult) error {
	return x.ServerStream.SendMsg(m)
}

func _DemoService_Upload_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(DemoServiceServer).Upload(&demoServiceUploadServer{stream})
}

type DemoService_UploadServer interface {
	SendAndClose(*PongResponse) error
	Recv() (*PingRequest, error)
	grpc.ServerStream
}

type demoServiceUploadServer struct {
	grpc.ServerStream
}

func (x *demoServiceUploadServer) SendAndClose(m *PongResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *demoServiceUploadServer) Recv() (*PingRequest, error) {
	m := new(PingRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _DemoService_Chat_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(DemoServiceServer).Chat(&demoServiceChatServer{stream})
}

type DemoService_ChatServer interface {
	Send(*PongResponse) error
	Recv() (*PingRequest, error)
	grpc.ServerStream
}

type demoServiceChatServer struct {
	grpc.ServerStream
}

func (x *demoServiceChatServer) Send(m *PongResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *demoServiceChatServer) Recv() (*PingRequest, error) {
	m := new(PingRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// DemoService_ServiceDesc is the grpc.ServiceDesc for DemoService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DemoService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "stream_test.DemoService",
	HandlerType: (*DemoServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Ping",
			Handler:    _DemoService_Ping_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Search",
			Handler:       _DemoService_Search_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "Upload",
			Handler:       _DemoService_Upload_Handler,
			ClientStreams: true,
		},
		{
			StreamName:    "Chat",
			Handler:       _DemoService_Chat_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "stream.proto",
}
