//
// Copyright 2024 hopeio. All rights reserved.
// Licensed under the MIT License that can be found in the LICENSE file.
// @Created by jyb

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.32.0
// source: hopeio/any/any.proto

package any

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Encoding int32

const (
	Encoding_JSON Encoding = 0
)

// Enum value maps for Encoding.
var (
	Encoding_name = map[int32]string{
		0: "JSON",
	}
	Encoding_value = map[string]int32{
		"JSON": 0,
	}
)

func (x Encoding) Enum() *Encoding {
	p := new(Encoding)
	*p = x
	return p
}

func (x Encoding) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Encoding) Descriptor() protoreflect.EnumDescriptor {
	return file_hopeio_any_any_proto_enumTypes[0].Descriptor()
}

func (Encoding) Type() protoreflect.EnumType {
	return &file_hopeio_any_any_proto_enumTypes[0]
}

func (x Encoding) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Encoding.Descriptor instead.
func (Encoding) EnumDescriptor() ([]byte, []int) {
	return file_hopeio_any_any_proto_rawDescGZIP(), []int{0}
}

type RawData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []byte                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RawData) Reset() {
	*x = RawData{}
	mi := &file_hopeio_any_any_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RawData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RawData) ProtoMessage() {}

func (x *RawData) ProtoReflect() protoreflect.Message {
	mi := &file_hopeio_any_any_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RawData.ProtoReflect.Descriptor instead.
func (*RawData) Descriptor() ([]byte, []int) {
	return file_hopeio_any_any_proto_rawDescGZIP(), []int{0}
}

func (x *RawData) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type RawEncodingData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []byte                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	Encoding      Encoding               `protobuf:"varint,2,opt,name=encoding,proto3,enum=any.Encoding" json:"encoding,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RawEncodingData) Reset() {
	*x = RawEncodingData{}
	mi := &file_hopeio_any_any_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RawEncodingData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RawEncodingData) ProtoMessage() {}

func (x *RawEncodingData) ProtoReflect() protoreflect.Message {
	mi := &file_hopeio_any_any_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RawEncodingData.ProtoReflect.Descriptor instead.
func (*RawEncodingData) Descriptor() ([]byte, []int) {
	return file_hopeio_any_any_proto_rawDescGZIP(), []int{1}
}

func (x *RawEncodingData) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *RawEncodingData) GetEncoding() Encoding {
	if x != nil {
		return x.Encoding
	}
	return Encoding_JSON
}

var File_hopeio_any_any_proto protoreflect.FileDescriptor

const file_hopeio_any_any_proto_rawDesc = "" +
	"\n" +
	"\x14hopeio/any/any.proto\x12\x03any\"\x1d\n" +
	"\aRawData\x12\x12\n" +
	"\x04data\x18\x01 \x01(\fR\x04data\"P\n" +
	"\x0fRawEncodingData\x12\x12\n" +
	"\x04data\x18\x01 \x01(\fR\x04data\x12)\n" +
	"\bencoding\x18\x02 \x01(\x0e2\r.any.EncodingR\bencoding*\x14\n" +
	"\bEncoding\x12\b\n" +
	"\x04JSON\x10\x00B:\n" +
	"\x16xyz.hoper.protobuf.anyP\x01Z\x1egithub.com/hopeio/protobuf/anyb\x06proto3"

var (
	file_hopeio_any_any_proto_rawDescOnce sync.Once
	file_hopeio_any_any_proto_rawDescData []byte
)

func file_hopeio_any_any_proto_rawDescGZIP() []byte {
	file_hopeio_any_any_proto_rawDescOnce.Do(func() {
		file_hopeio_any_any_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_hopeio_any_any_proto_rawDesc), len(file_hopeio_any_any_proto_rawDesc)))
	})
	return file_hopeio_any_any_proto_rawDescData
}

var file_hopeio_any_any_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_hopeio_any_any_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_hopeio_any_any_proto_goTypes = []any{
	(Encoding)(0),           // 0: any.Encoding
	(*RawData)(nil),         // 1: any.RawData
	(*RawEncodingData)(nil), // 2: any.RawEncodingData
}
var file_hopeio_any_any_proto_depIdxs = []int32{
	0, // 0: any.RawEncodingData.encoding:type_name -> any.Encoding
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_hopeio_any_any_proto_init() }
func file_hopeio_any_any_proto_init() {
	if File_hopeio_any_any_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_hopeio_any_any_proto_rawDesc), len(file_hopeio_any_any_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_hopeio_any_any_proto_goTypes,
		DependencyIndexes: file_hopeio_any_any_proto_depIdxs,
		EnumInfos:         file_hopeio_any_any_proto_enumTypes,
		MessageInfos:      file_hopeio_any_any_proto_msgTypes,
	}.Build()
	File_hopeio_any_any_proto = out.File
	file_hopeio_any_any_proto_goTypes = nil
	file_hopeio_any_any_proto_depIdxs = nil
}
