//
// Copyright 2024 hopeio. All rights reserved.
// Licensed under the MIT License that can be found in the LICENSE file.
// @Created by jyb

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.32.0
// source: hopeio/model/time/model.proto

package model

import (
	time "github.com/hopeio/protobuf/time"
	deletedAt "github.com/hopeio/protobuf/time/deletedAt"
	_ "github.com/hopeio/protobuf/utils/patch"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ModelTimeStr struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CreatedAt     string                 `protobuf:"bytes,1,opt,name=createdAt,proto3" json:"createdAt,omitempty" gorm:"type:timestamptz(6);default:now();index"`
	UpdatedAt     string                 `protobuf:"bytes,2,opt,name=updatedAt,proto3" json:"updatedAt,omitempty" gorm:"type:timestamptz(6)"`
	DeletedAt     string                 `protobuf:"bytes,3,opt,name=deletedAt,proto3" json:"deletedAt,omitempty" gorm:"<-:false;type:timestamptz(6);index"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ModelTimeStr) Reset() {
	*x = ModelTimeStr{}
	mi := &file_hopeio_model_time_model_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ModelTimeStr) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ModelTimeStr) ProtoMessage() {}

func (x *ModelTimeStr) ProtoReflect() protoreflect.Message {
	mi := &file_hopeio_model_time_model_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ModelTimeStr.ProtoReflect.Descriptor instead.
func (*ModelTimeStr) Descriptor() ([]byte, []int) {
	return file_hopeio_model_time_model_proto_rawDescGZIP(), []int{0}
}

func (x *ModelTimeStr) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *ModelTimeStr) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

func (x *ModelTimeStr) GetDeletedAt() string {
	if x != nil {
		return x.DeletedAt
	}
	return ""
}

type ModelTimeStamp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CreatedAt     int64                  `protobuf:"varint,1,opt,name=createdAt,proto3" json:"createdAt,omitempty" gorm:"type:timestamptz(6);default:now();index"`
	UpdatedAt     int64                  `protobuf:"varint,2,opt,name=updatedAt,proto3" json:"updatedAt,omitempty" gorm:"type:timestamptz(6)"`
	DeletedAt     int64                  `protobuf:"varint,3,opt,name=deletedAt,proto3" json:"deletedAt,omitempty" gorm:"<-:false;type:timestamptz(6);index"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ModelTimeStamp) Reset() {
	*x = ModelTimeStamp{}
	mi := &file_hopeio_model_time_model_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ModelTimeStamp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ModelTimeStamp) ProtoMessage() {}

func (x *ModelTimeStamp) ProtoReflect() protoreflect.Message {
	mi := &file_hopeio_model_time_model_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ModelTimeStamp.ProtoReflect.Descriptor instead.
func (*ModelTimeStamp) Descriptor() ([]byte, []int) {
	return file_hopeio_model_time_model_proto_rawDescGZIP(), []int{1}
}

func (x *ModelTimeStamp) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *ModelTimeStamp) GetUpdatedAt() int64 {
	if x != nil {
		return x.UpdatedAt
	}
	return 0
}

func (x *ModelTimeStamp) GetDeletedAt() int64 {
	if x != nil {
		return x.DeletedAt
	}
	return 0
}

type ModelTime struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CreatedAt     *time.Time             `protobuf:"bytes,1,opt,name=createdAt,proto3" json:"createdAt,omitempty" gorm:"type:timestamptz(6);default:now()"`
	UpdatedAt     *time.Time             `protobuf:"bytes,2,opt,name=updatedAt,proto3" json:"updatedAt,omitempty" gorm:"type:timestamptz(6)"`
	DeletedAt     *deletedAt.DeletedAt   `protobuf:"bytes,3,opt,name=deletedAt,proto3" json:"deletedAt,omitempty" gorm:"<-:false;type:timestamptz(6);index"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ModelTime) Reset() {
	*x = ModelTime{}
	mi := &file_hopeio_model_time_model_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ModelTime) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ModelTime) ProtoMessage() {}

func (x *ModelTime) ProtoReflect() protoreflect.Message {
	mi := &file_hopeio_model_time_model_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ModelTime.ProtoReflect.Descriptor instead.
func (*ModelTime) Descriptor() ([]byte, []int) {
	return file_hopeio_model_time_model_proto_rawDescGZIP(), []int{2}
}

func (x *ModelTime) GetCreatedAt() *time.Time {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *ModelTime) GetUpdatedAt() *time.Time {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *ModelTime) GetDeletedAt() *deletedAt.DeletedAt {
	if x != nil {
		return x.DeletedAt
	}
	return nil
}

var File_hopeio_model_time_model_proto protoreflect.FileDescriptor

const file_hopeio_model_time_model_proto_rawDesc = "" +
	"\n" +
	"\x1dhopeio/model/time/model.proto\x12\n" +
	"time.model\x1a\x1bhopeio/utils/patch/go.proto\x1a\x16hopeio/time/time.proto\x1a%hopeio/time/deletedAt/deletedAt.proto\"\xf4\x01\n" +
	"\fModelTimeStr\x12S\n" +
	"\tcreatedAt\x18\x01 \x01(\tB5ҵ\x031\xa2\x01.gorm:\"type:timestamptz(6);default:now();index\"R\tcreatedAt\x12?\n" +
	"\tupdatedAt\x18\x02 \x01(\tB!ҵ\x03\x1d\xa2\x01\x1agorm:\"type:timestamptz(6)\"R\tupdatedAt\x12N\n" +
	"\tdeletedAt\x18\x03 \x01(\tB0ҵ\x03,\xa2\x01)gorm:\"<-:false;type:timestamptz(6);index\"R\tdeletedAt\"\xf6\x01\n" +
	"\x0eModelTimeStamp\x12S\n" +
	"\tcreatedAt\x18\x01 \x01(\x03B5ҵ\x031\xa2\x01.gorm:\"type:timestamptz(6);default:now();index\"R\tcreatedAt\x12?\n" +
	"\tupdatedAt\x18\x02 \x01(\x03B!ҵ\x03\x1d\xa2\x01\x1agorm:\"type:timestamptz(6)\"R\tupdatedAt\x12N\n" +
	"\tdeletedAt\x18\x03 \x01(\x03B0ҵ\x03,\xa2\x01)gorm:\"<-:false;type:timestamptz(6);index\"R\tdeletedAt\"\x99\x02\n" +
	"\tModelTime\x12Y\n" +
	"\tcreatedAt\x18\x01 \x01(\v2\n" +
	".time.TimeB/ҵ\x03+\xa2\x01(gorm:\"type:timestamptz(6);default:now()\"R\tcreatedAt\x12K\n" +
	"\tupdatedAt\x18\x02 \x01(\v2\n" +
	".time.TimeB!ҵ\x03\x1d\xa2\x01\x1agorm:\"type:timestamptz(6)\"R\tupdatedAt\x12d\n" +
	"\tdeletedAt\x18\x03 \x01(\v2\x14.deletedAt.DeletedAtB0ҵ\x03,\xa2\x01)gorm:\"<-:false;type:timestamptz(6);index\"R\tdeletedAtBH\n" +
	"\x1dxyz.hoper.protobuf.time.modelP\x01Z%github.com/hopeio/protobuf/time/modelb\x06proto3"

var (
	file_hopeio_model_time_model_proto_rawDescOnce sync.Once
	file_hopeio_model_time_model_proto_rawDescData []byte
)

func file_hopeio_model_time_model_proto_rawDescGZIP() []byte {
	file_hopeio_model_time_model_proto_rawDescOnce.Do(func() {
		file_hopeio_model_time_model_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_hopeio_model_time_model_proto_rawDesc), len(file_hopeio_model_time_model_proto_rawDesc)))
	})
	return file_hopeio_model_time_model_proto_rawDescData
}

var file_hopeio_model_time_model_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_hopeio_model_time_model_proto_goTypes = []any{
	(*ModelTimeStr)(nil),        // 0: time.model.ModelTimeStr
	(*ModelTimeStamp)(nil),      // 1: time.model.ModelTimeStamp
	(*ModelTime)(nil),           // 2: time.model.ModelTime
	(*time.Time)(nil),           // 3: time.Time
	(*deletedAt.DeletedAt)(nil), // 4: deletedAt.DeletedAt
}
var file_hopeio_model_time_model_proto_depIdxs = []int32{
	3, // 0: time.model.ModelTime.createdAt:type_name -> time.Time
	3, // 1: time.model.ModelTime.updatedAt:type_name -> time.Time
	4, // 2: time.model.ModelTime.deletedAt:type_name -> deletedAt.DeletedAt
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_hopeio_model_time_model_proto_init() }
func file_hopeio_model_time_model_proto_init() {
	if File_hopeio_model_time_model_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_hopeio_model_time_model_proto_rawDesc), len(file_hopeio_model_time_model_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_hopeio_model_time_model_proto_goTypes,
		DependencyIndexes: file_hopeio_model_time_model_proto_depIdxs,
		MessageInfos:      file_hopeio_model_time_model_proto_msgTypes,
	}.Build()
	File_hopeio_model_time_model_proto = out.File
	file_hopeio_model_time_model_proto_goTypes = nil
	file_hopeio_model_time_model_proto_depIdxs = nil
}
