//
// Copyright 2024 hopeio. All rights reserved.
// Licensed under the MIT License that can be found in the LICENSE file.
// @Created by jyb

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.32.0
// source: hopeio/response/response.proto

package response

import (
	any1 "github.com/hopeio/protobuf/any"
	_ "github.com/hopeio/protobuf/utils/patch"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	anypb "google.golang.org/protobuf/types/known/anypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AnyResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code"`
	Msg           string                 `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	Data          *anypb.Any             `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AnyResp) Reset() {
	*x = AnyResp{}
	mi := &file_hopeio_response_response_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AnyResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnyResp) ProtoMessage() {}

func (x *AnyResp) ProtoReflect() protoreflect.Message {
	mi := &file_hopeio_response_response_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnyResp.ProtoReflect.Descriptor instead.
func (*AnyResp) Descriptor() ([]byte, []int) {
	return file_hopeio_response_response_proto_rawDescGZIP(), []int{0}
}

func (x *AnyResp) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *AnyResp) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *AnyResp) GetData() *anypb.Any {
	if x != nil {
		return x.Data
	}
	return nil
}

type RawResp struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Code  int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code"`
	Msg   string                 `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	// 字节数组json
	Data          *any1.RawData `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RawResp) Reset() {
	*x = RawResp{}
	mi := &file_hopeio_response_response_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RawResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RawResp) ProtoMessage() {}

func (x *RawResp) ProtoReflect() protoreflect.Message {
	mi := &file_hopeio_response_response_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RawResp.ProtoReflect.Descriptor instead.
func (*RawResp) Descriptor() ([]byte, []int) {
	return file_hopeio_response_response_proto_rawDescGZIP(), []int{1}
}

func (x *RawResp) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *RawResp) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *RawResp) GetData() *any1.RawData {
	if x != nil {
		return x.Data
	}
	return nil
}

// 返回数据为字符串，用于新建修改删除类的成功失败提示
type CommonResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code"`
	Msg           string                 `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommonResp) Reset() {
	*x = CommonResp{}
	mi := &file_hopeio_response_response_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommonResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommonResp) ProtoMessage() {}

func (x *CommonResp) ProtoReflect() protoreflect.Message {
	mi := &file_hopeio_response_response_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommonResp.ProtoReflect.Descriptor instead.
func (*CommonResp) Descriptor() ([]byte, []int) {
	return file_hopeio_response_response_proto_rawDescGZIP(), []int{2}
}

func (x *CommonResp) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *CommonResp) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

type HttpResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Headers       map[string]string      `protobuf:"bytes,1,rep,name=headers,proto3" json:"headers,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Body          []byte                 `protobuf:"bytes,2,opt,name=body,proto3" json:"body,omitempty"`
	Status        int32                  `protobuf:"varint,3,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HttpResponse) Reset() {
	*x = HttpResponse{}
	mi := &file_hopeio_response_response_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HttpResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HttpResponse) ProtoMessage() {}

func (x *HttpResponse) ProtoReflect() protoreflect.Message {
	mi := &file_hopeio_response_response_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HttpResponse.ProtoReflect.Descriptor instead.
func (*HttpResponse) Descriptor() ([]byte, []int) {
	return file_hopeio_response_response_proto_rawDescGZIP(), []int{3}
}

func (x *HttpResponse) GetHeaders() map[string]string {
	if x != nil {
		return x.Headers
	}
	return nil
}

func (x *HttpResponse) GetBody() []byte {
	if x != nil {
		return x.Body
	}
	return nil
}

func (x *HttpResponse) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

var File_hopeio_response_response_proto protoreflect.FileDescriptor

const file_hopeio_response_response_proto_rawDesc = "" +
	"\n" +
	"\x1ehopeio/response/response.proto\x12\bresponse\x1a\x19google/protobuf/any.proto\x1a\x14hopeio/any/any.proto\x1a\x1bhopeio/utils/patch/go.proto\"m\n" +
	"\aAnyResp\x12&\n" +
	"\x04code\x18\x01 \x01(\x05B\x12ҵ\x03\x0e\xa2\x01\vjson:\"code\"R\x04code\x12\x10\n" +
	"\x03msg\x18\x02 \x01(\tR\x03msg\x12(\n" +
	"\x04data\x18\x03 \x01(\v2\x14.google.protobuf.AnyR\x04data\"e\n" +
	"\aRawResp\x12&\n" +
	"\x04code\x18\x01 \x01(\x05B\x12ҵ\x03\x0e\xa2\x01\vjson:\"code\"R\x04code\x12\x10\n" +
	"\x03msg\x18\x02 \x01(\tR\x03msg\x12 \n" +
	"\x04data\x18\x03 \x01(\v2\f.any.RawDataR\x04data\"F\n" +
	"\n" +
	"CommonResp\x12&\n" +
	"\x04code\x18\x01 \x01(\x05B\x12ҵ\x03\x0e\xa2\x01\vjson:\"code\"R\x04code\x12\x10\n" +
	"\x03msg\x18\x02 \x01(\tR\x03msg\"\xb5\x01\n" +
	"\fHttpResponse\x12=\n" +
	"\aheaders\x18\x01 \x03(\v2#.response.HttpResponse.HeadersEntryR\aheaders\x12\x12\n" +
	"\x04body\x18\x02 \x01(\fR\x04body\x12\x16\n" +
	"\x06status\x18\x03 \x01(\x05R\x06status\x1a:\n" +
	"\fHeadersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01BD\n" +
	"\x1bxyz.hoper.protobuf.responseP\x01Z#github.com/hopeio/protobuf/responseb\x06proto3"

var (
	file_hopeio_response_response_proto_rawDescOnce sync.Once
	file_hopeio_response_response_proto_rawDescData []byte
)

func file_hopeio_response_response_proto_rawDescGZIP() []byte {
	file_hopeio_response_response_proto_rawDescOnce.Do(func() {
		file_hopeio_response_response_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_hopeio_response_response_proto_rawDesc), len(file_hopeio_response_response_proto_rawDesc)))
	})
	return file_hopeio_response_response_proto_rawDescData
}

var file_hopeio_response_response_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_hopeio_response_response_proto_goTypes = []any{
	(*AnyResp)(nil),      // 0: response.AnyResp
	(*RawResp)(nil),      // 1: response.RawResp
	(*CommonResp)(nil),   // 2: response.CommonResp
	(*HttpResponse)(nil), // 3: response.HttpResponse
	nil,                  // 4: response.HttpResponse.HeadersEntry
	(*anypb.Any)(nil),    // 5: google.protobuf.Any
	(*any1.RawData)(nil), // 6: any.RawData
}
var file_hopeio_response_response_proto_depIdxs = []int32{
	5, // 0: response.AnyResp.data:type_name -> google.protobuf.Any
	6, // 1: response.RawResp.data:type_name -> any.RawData
	4, // 2: response.HttpResponse.headers:type_name -> response.HttpResponse.HeadersEntry
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_hopeio_response_response_proto_init() }
func file_hopeio_response_response_proto_init() {
	if File_hopeio_response_response_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_hopeio_response_response_proto_rawDesc), len(file_hopeio_response_response_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_hopeio_response_response_proto_goTypes,
		DependencyIndexes: file_hopeio_response_response_proto_depIdxs,
		MessageInfos:      file_hopeio_response_response_proto_msgTypes,
	}.Build()
	File_hopeio_response_response_proto = out.File
	file_hopeio_response_response_proto_goTypes = nil
	file_hopeio_response_response_proto_depIdxs = nil
}
