//
// Copyright 2024 hopeio. All rights reserved.
// Licensed under the MIT License that can be found in the LICENSE file.
// @Created by jyb

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.28.3
// source: hopeio/utils/enum/enum.proto

package enum

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	descriptorpb "google.golang.org/protobuf/types/descriptorpb"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var file_hopeio_utils_enum_enum_proto_extTypes = []protoimpl.ExtensionInfo{
	{
		ExtendedType:  (*descriptorpb.EnumOptions)(nil),
		ExtensionType: (*string)(nil),
		Field:         62025,
		Name:          "enum.customtype",
		Tag:           "bytes,62025,opt,name=customtype",
		Filename:      "hopeio/utils/enum/enum.proto",
	},
	{
		ExtendedType:  (*descriptorpb.EnumOptions)(nil),
		ExtensionType: (*bool)(nil),
		Field:         62026,
		Name:          "enum.no_genvaluemap",
		Tag:           "varint,62026,opt,name=no_genvaluemap",
		Filename:      "hopeio/utils/enum/enum.proto",
	},
	{
		ExtendedType:  (*descriptorpb.EnumOptions)(nil),
		ExtensionType: (*bool)(nil),
		Field:         62027,
		Name:          "enum.numorder",
		Tag:           "varint,62027,opt,name=numorder",
		Filename:      "hopeio/utils/enum/enum.proto",
	},
	{
		ExtendedType:  (*descriptorpb.EnumOptions)(nil),
		ExtensionType: (*bool)(nil),
		Field:         62028,
		Name:          "enum.jsonmarshal",
		Tag:           "varint,62028,opt,name=jsonmarshal",
		Filename:      "hopeio/utils/enum/enum.proto",
	},
	{
		ExtendedType:  (*descriptorpb.EnumOptions)(nil),
		ExtensionType: (*bool)(nil),
		Field:         62029,
		Name:          "enum.errcode",
		Tag:           "varint,62029,opt,name=errcode",
		Filename:      "hopeio/utils/enum/enum.proto",
	},
	{
		ExtendedType:  (*descriptorpb.EnumOptions)(nil),
		ExtensionType: (*bool)(nil),
		Field:         62030,
		Name:          "enum.gqlgen",
		Tag:           "varint,62030,opt,name=gqlgen",
		Filename:      "hopeio/utils/enum/enum.proto",
	},
	{
		ExtendedType:  (*descriptorpb.EnumOptions)(nil),
		ExtensionType: (*bool)(nil),
		Field:         62031,
		Name:          "enum.no_prefix",
		Tag:           "varint,62031,opt,name=no_prefix",
		Filename:      "hopeio/utils/enum/enum.proto",
	},
	{
		ExtendedType:  (*descriptorpb.EnumOptions)(nil),
		ExtensionType: (*bool)(nil),
		Field:         62032,
		Name:          "enum.no_extgen",
		Tag:           "varint,62032,opt,name=no_extgen",
		Filename:      "hopeio/utils/enum/enum.proto",
	},
	{
		ExtendedType:  (*descriptorpb.EnumOptions)(nil),
		ExtensionType: (*bool)(nil),
		Field:         62034,
		Name:          "enum.textmarshal",
		Tag:           "varint,62034,opt,name=textmarshal",
		Filename:      "hopeio/utils/enum/enum.proto",
	},
	{
		ExtendedType:  (*descriptorpb.EnumValueOptions)(nil),
		ExtensionType: (*string)(nil),
		Field:         66002,
		Name:          "enum.text",
		Tag:           "bytes,66002,opt,name=text",
		Filename:      "hopeio/utils/enum/enum.proto",
	},
	{
		ExtendedType:  (*descriptorpb.FileOptions)(nil),
		ExtensionType: (*bool)(nil),
		Field:         1001,
		Name:          "enum.gqlgen_all",
		Tag:           "varint,1001,opt,name=gqlgen_all",
		Filename:      "hopeio/utils/enum/enum.proto",
	},
	{
		ExtendedType:  (*descriptorpb.FileOptions)(nil),
		ExtensionType: (*bool)(nil),
		Field:         1003,
		Name:          "enum.jsonmarshal_all",
		Tag:           "varint,1003,opt,name=jsonmarshal_all",
		Filename:      "hopeio/utils/enum/enum.proto",
	},
	{
		ExtendedType:  (*descriptorpb.FileOptions)(nil),
		ExtensionType: (*bool)(nil),
		Field:         1004,
		Name:          "enum.textmarshal_all",
		Tag:           "varint,1004,opt,name=textmarshal_all",
		Filename:      "hopeio/utils/enum/enum.proto",
	},
	{
		ExtendedType:  (*descriptorpb.FileOptions)(nil),
		ExtensionType: (*bool)(nil),
		Field:         1002,
		Name:          "enum.no_prefix_all",
		Tag:           "varint,1002,opt,name=no_prefix_all",
		Filename:      "hopeio/utils/enum/enum.proto",
	},
	{
		ExtendedType:  (*descriptorpb.FileOptions)(nil),
		ExtensionType: (*bool)(nil),
		Field:         1005,
		Name:          "enum.no_extgen_all",
		Tag:           "varint,1005,opt,name=no_extgen_all",
		Filename:      "hopeio/utils/enum/enum.proto",
	},
}

// Extension fields to descriptorpb.EnumOptions.
var (
	// 自定义类型
	//
	// optional string customtype = 62025;
	E_Customtype = &file_hopeio_utils_enum_enum_proto_extTypes[0]
	// optional bool no_genvaluemap = 62026;
	E_NoGenvaluemap = &file_hopeio_utils_enum_enum_proto_extTypes[1]
	// 不用手动标序号，= iota
	//
	// optional bool numorder = 62027;
	E_Numorder = &file_hopeio_utils_enum_enum_proto_extTypes[2]
	// 生成JsonMarshal
	//
	// optional bool jsonmarshal = 62028;
	E_Jsonmarshal = &file_hopeio_utils_enum_enum_proto_extTypes[3]
	// 是errcode
	//
	// optional bool errcode = 62029;
	E_Errcode = &file_hopeio_utils_enum_enum_proto_extTypes[4]
	// optional bool gqlgen = 62030;
	E_Gqlgen = &file_hopeio_utils_enum_enum_proto_extTypes[5]
	// optional bool no_prefix = 62031;
	E_NoPrefix = &file_hopeio_utils_enum_enum_proto_extTypes[6]
	// optional bool no_extgen = 62032;
	E_NoExtgen = &file_hopeio_utils_enum_enum_proto_extTypes[7]
	// optional bool textmarshal = 62034;
	E_Textmarshal = &file_hopeio_utils_enum_enum_proto_extTypes[8]
)

// Extension fields to descriptorpb.EnumValueOptions.
var (
	// optional string text = 66002;
	E_Text = &file_hopeio_utils_enum_enum_proto_extTypes[9]
)

// Extension fields to descriptorpb.FileOptions.
var (
	// optional bool gqlgen_all = 1001;
	E_GqlgenAll = &file_hopeio_utils_enum_enum_proto_extTypes[10]
	// optional bool jsonmarshal_all = 1003;
	E_JsonmarshalAll = &file_hopeio_utils_enum_enum_proto_extTypes[11]
	// optional bool textmarshal_all = 1004;
	E_TextmarshalAll = &file_hopeio_utils_enum_enum_proto_extTypes[12]
	// optional bool no_prefix_all = 1002;
	E_NoPrefixAll = &file_hopeio_utils_enum_enum_proto_extTypes[13]
	// optional bool no_extgen_all = 1005;
	E_NoExtgenAll = &file_hopeio_utils_enum_enum_proto_extTypes[14]
)

var File_hopeio_utils_enum_enum_proto protoreflect.FileDescriptor

const file_hopeio_utils_enum_enum_proto_rawDesc = "" +
	"\n" +
	"\x1chopeio/utils/enum/enum.proto\x12\x04enum\x1a google/protobuf/descriptor.proto:>\n" +
	"\n" +
	"customtype\x12\x1c.google.protobuf.EnumOptions\x18\xc9\xe4\x03 \x01(\tR\n" +
	"customtype:E\n" +
	"\x0eno_genvaluemap\x12\x1c.google.protobuf.EnumOptions\x18\xca\xe4\x03 \x01(\bR\rnoGenvaluemap::\n" +
	"\bnumorder\x12\x1c.google.protobuf.EnumOptions\x18\xcb\xe4\x03 \x01(\bR\bnumorder:@\n" +
	"\vjsonmarshal\x12\x1c.google.protobuf.EnumOptions\x18\xcc\xe4\x03 \x01(\bR\vjsonmarshal:8\n" +
	"\aerrcode\x12\x1c.google.protobuf.EnumOptions\x18\xcd\xe4\x03 \x01(\bR\aerrcode:6\n" +
	"\x06gqlgen\x12\x1c.google.protobuf.EnumOptions\x18\xce\xe4\x03 \x01(\bR\x06gqlgen:;\n" +
	"\tno_prefix\x12\x1c.google.protobuf.EnumOptions\x18\xcf\xe4\x03 \x01(\bR\bnoPrefix:;\n" +
	"\tno_extgen\x12\x1c.google.protobuf.EnumOptions\x18\xd0\xe4\x03 \x01(\bR\bnoExtgen:@\n" +
	"\vtextmarshal\x12\x1c.google.protobuf.EnumOptions\x18\xd2\xe4\x03 \x01(\bR\vtextmarshal:7\n" +
	"\x04text\x12!.google.protobuf.EnumValueOptions\x18҃\x04 \x01(\tR\x04text:<\n" +
	"\n" +
	"gqlgen_all\x12\x1c.google.protobuf.FileOptions\x18\xe9\a \x01(\bR\tgqlgenAll:F\n" +
	"\x0fjsonmarshal_all\x12\x1c.google.protobuf.FileOptions\x18\xeb\a \x01(\bR\x0ejsonmarshalAll:F\n" +
	"\x0ftextmarshal_all\x12\x1c.google.protobuf.FileOptions\x18\xec\a \x01(\bR\x0etextmarshalAll:A\n" +
	"\rno_prefix_all\x12\x1c.google.protobuf.FileOptions\x18\xea\a \x01(\bR\vnoPrefixAll:A\n" +
	"\rno_extgen_all\x12\x1c.google.protobuf.FileOptions\x18\xed\a \x01(\bR\vnoExtgenAllBS\n" +
	"\x1exyz.hoper.protobuf.utils.enumsB\n" +
	"EnumProtosZ%github.com/hopeio/protobuf/utils/enum"

var file_hopeio_utils_enum_enum_proto_goTypes = []any{
	(*descriptorpb.EnumOptions)(nil),      // 0: google.protobuf.EnumOptions
	(*descriptorpb.EnumValueOptions)(nil), // 1: google.protobuf.EnumValueOptions
	(*descriptorpb.FileOptions)(nil),      // 2: google.protobuf.FileOptions
}
var file_hopeio_utils_enum_enum_proto_depIdxs = []int32{
	0,  // 0: enum.customtype:extendee -> google.protobuf.EnumOptions
	0,  // 1: enum.no_genvaluemap:extendee -> google.protobuf.EnumOptions
	0,  // 2: enum.numorder:extendee -> google.protobuf.EnumOptions
	0,  // 3: enum.jsonmarshal:extendee -> google.protobuf.EnumOptions
	0,  // 4: enum.errcode:extendee -> google.protobuf.EnumOptions
	0,  // 5: enum.gqlgen:extendee -> google.protobuf.EnumOptions
	0,  // 6: enum.no_prefix:extendee -> google.protobuf.EnumOptions
	0,  // 7: enum.no_extgen:extendee -> google.protobuf.EnumOptions
	0,  // 8: enum.textmarshal:extendee -> google.protobuf.EnumOptions
	1,  // 9: enum.text:extendee -> google.protobuf.EnumValueOptions
	2,  // 10: enum.gqlgen_all:extendee -> google.protobuf.FileOptions
	2,  // 11: enum.jsonmarshal_all:extendee -> google.protobuf.FileOptions
	2,  // 12: enum.textmarshal_all:extendee -> google.protobuf.FileOptions
	2,  // 13: enum.no_prefix_all:extendee -> google.protobuf.FileOptions
	2,  // 14: enum.no_extgen_all:extendee -> google.protobuf.FileOptions
	15, // [15:15] is the sub-list for method output_type
	15, // [15:15] is the sub-list for method input_type
	15, // [15:15] is the sub-list for extension type_name
	0,  // [0:15] is the sub-list for extension extendee
	0,  // [0:0] is the sub-list for field type_name
}

func init() { file_hopeio_utils_enum_enum_proto_init() }
func file_hopeio_utils_enum_enum_proto_init() {
	if File_hopeio_utils_enum_enum_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_hopeio_utils_enum_enum_proto_rawDesc), len(file_hopeio_utils_enum_enum_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 15,
			NumServices:   0,
		},
		GoTypes:           file_hopeio_utils_enum_enum_proto_goTypes,
		DependencyIndexes: file_hopeio_utils_enum_enum_proto_depIdxs,
		ExtensionInfos:    file_hopeio_utils_enum_enum_proto_extTypes,
	}.Build()
	File_hopeio_utils_enum_enum_proto = out.File
	file_hopeio_utils_enum_enum_proto_goTypes = nil
	file_hopeio_utils_enum_enum_proto_depIdxs = nil
}
