// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.1
// source: hopeio/utils/patch/go.proto

package patch

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	descriptorpb "google.golang.org/protobuf/types/descriptorpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Options represent Go-specific options for Protobuf messages, fields, oneofs, enums, or enum values.
type Options struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The name option renames the generated Go identifier and related identifiers.
	// For a message, this renames the generated Go struct and nested messages or enums, if any.
	// For a message field, this renames the generated Go struct field and getter method.
	// For a oneof field, this renames the generated Go struct field, getter method, interface type, and wrapper types.
	// For an enum, this renames the generated Go type.
	// For an enum value, this renames the generated Go const.
	Name *string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	// The getter_name option renames the generated getter method (default: Get<Field>)
	// so a custom getter can be implemented in its place.
	GetterName *string `protobuf:"bytes,10,opt,name=getter_name,json=getterName" json:"getter_name,omitempty"` // TODO: implement this
	// The tags option specifies additional struct tags which are appended a generated Go struct field.
	// This option may be specified on a message field or a oneof field.
	// The value should omit the enclosing backticks.
	Tags *string `protobuf:"bytes,20,opt,name=tags" json:"tags,omitempty"`
	// The stringer_name option renames a generated String() method (if any)
	// so a custom String() method can be implemented in its place.
	StringerName  *string `protobuf:"bytes,30,opt,name=stringer_name,json=stringerName" json:"stringer_name,omitempty"` // TODO: implement for messages
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Options) Reset() {
	*x = Options{}
	mi := &file_hopeio_utils_patch_go_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Options) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Options) ProtoMessage() {}

func (x *Options) ProtoReflect() protoreflect.Message {
	mi := &file_hopeio_utils_patch_go_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Options.ProtoReflect.Descriptor instead.
func (*Options) Descriptor() ([]byte, []int) {
	return file_hopeio_utils_patch_go_proto_rawDescGZIP(), []int{0}
}

func (x *Options) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

func (x *Options) GetGetterName() string {
	if x != nil && x.GetterName != nil {
		return *x.GetterName
	}
	return ""
}

func (x *Options) GetTags() string {
	if x != nil && x.Tags != nil {
		return *x.Tags
	}
	return ""
}

func (x *Options) GetStringerName() string {
	if x != nil && x.StringerName != nil {
		return *x.StringerName
	}
	return ""
}

type FileOptions struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NoOmitempty   *bool                  `protobuf:"varint,1,opt,name=no_omitempty,json=noOmitempty" json:"no_omitempty,omitempty"`
	NoEnumPrefix  *bool                  `protobuf:"varint,10,opt,name=no_enum_prefix,json=noEnumPrefix" json:"no_enum_prefix,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileOptions) Reset() {
	*x = FileOptions{}
	mi := &file_hopeio_utils_patch_go_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileOptions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileOptions) ProtoMessage() {}

func (x *FileOptions) ProtoReflect() protoreflect.Message {
	mi := &file_hopeio_utils_patch_go_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileOptions.ProtoReflect.Descriptor instead.
func (*FileOptions) Descriptor() ([]byte, []int) {
	return file_hopeio_utils_patch_go_proto_rawDescGZIP(), []int{1}
}

func (x *FileOptions) GetNoOmitempty() bool {
	if x != nil && x.NoOmitempty != nil {
		return *x.NoOmitempty
	}
	return false
}

func (x *FileOptions) GetNoEnumPrefix() bool {
	if x != nil && x.NoEnumPrefix != nil {
		return *x.NoEnumPrefix
	}
	return false
}

var file_hopeio_utils_patch_go_proto_extTypes = []protoimpl.ExtensionInfo{
	{
		ExtendedType:  (*descriptorpb.MessageOptions)(nil),
		ExtensionType: (*Options)(nil),
		Field:         7002,
		Name:          "go.message",
		Tag:           "bytes,7002,opt,name=message",
		Filename:      "hopeio/utils/patch/go.proto",
	},
	{
		ExtendedType:  (*descriptorpb.FieldOptions)(nil),
		ExtensionType: (*Options)(nil),
		Field:         7002,
		Name:          "go.field",
		Tag:           "bytes,7002,opt,name=field",
		Filename:      "hopeio/utils/patch/go.proto",
	},
	{
		ExtendedType:  (*descriptorpb.OneofOptions)(nil),
		ExtensionType: (*Options)(nil),
		Field:         7001,
		Name:          "go.oneof",
		Tag:           "bytes,7001,opt,name=oneof",
		Filename:      "hopeio/utils/patch/go.proto",
	},
	{
		ExtendedType:  (*descriptorpb.EnumOptions)(nil),
		ExtensionType: (*Options)(nil),
		Field:         7002,
		Name:          "go.enum",
		Tag:           "bytes,7002,opt,name=enum",
		Filename:      "hopeio/utils/patch/go.proto",
	},
	{
		ExtendedType:  (*descriptorpb.EnumValueOptions)(nil),
		ExtensionType: (*Options)(nil),
		Field:         7002,
		Name:          "go.value",
		Tag:           "bytes,7002,opt,name=value",
		Filename:      "hopeio/utils/patch/go.proto",
	},
	{
		ExtendedType:  (*descriptorpb.FileOptions)(nil),
		ExtensionType: (*FileOptions)(nil),
		Field:         7002,
		Name:          "go.file",
		Tag:           "bytes,7002,opt,name=file",
		Filename:      "hopeio/utils/patch/go.proto",
	},
}

// Extension fields to descriptorpb.MessageOptions.
var (
	// optional go.Options message = 7002;
	E_Message = &file_hopeio_utils_patch_go_proto_extTypes[0]
)

// Extension fields to descriptorpb.FieldOptions.
var (
	// optional go.Options field = 7002;
	E_Field = &file_hopeio_utils_patch_go_proto_extTypes[1]
)

// Extension fields to descriptorpb.OneofOptions.
var (
	// optional go.Options oneof = 7001;
	E_Oneof = &file_hopeio_utils_patch_go_proto_extTypes[2]
)

// Extension fields to descriptorpb.EnumOptions.
var (
	// optional go.Options enum = 7002;
	E_Enum = &file_hopeio_utils_patch_go_proto_extTypes[3]
)

// Extension fields to descriptorpb.EnumValueOptions.
var (
	// optional go.Options value = 7002;
	E_Value = &file_hopeio_utils_patch_go_proto_extTypes[4]
)

// Extension fields to descriptorpb.FileOptions.
var (
	// optional go.FileOptions file = 7002;
	E_File = &file_hopeio_utils_patch_go_proto_extTypes[5]
)

var File_hopeio_utils_patch_go_proto protoreflect.FileDescriptor

const file_hopeio_utils_patch_go_proto_rawDesc = "" +
	"\n" +
	"\x1bhopeio/utils/patch/go.proto\x12\x02go\x1a google/protobuf/descriptor.proto\"w\n" +
	"\aOptions\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1f\n" +
	"\vgetter_name\x18\n" +
	" \x01(\tR\n" +
	"getterName\x12\x12\n" +
	"\x04tags\x18\x14 \x01(\tR\x04tags\x12#\n" +
	"\rstringer_name\x18\x1e \x01(\tR\fstringerName\"V\n" +
	"\vFileOptions\x12!\n" +
	"\fno_omitempty\x18\x01 \x01(\bR\vnoOmitempty\x12$\n" +
	"\x0eno_enum_prefix\x18\n" +
	" \x01(\bR\fnoEnumPrefix:G\n" +
	"\amessage\x12\x1f.google.protobuf.MessageOptions\x18\xda6 \x01(\v2\v.go.OptionsR\amessage:A\n" +
	"\x05field\x12\x1d.google.protobuf.FieldOptions\x18\xda6 \x01(\v2\v.go.OptionsR\x05field:A\n" +
	"\x05oneof\x12\x1d.google.protobuf.OneofOptions\x18\xd96 \x01(\v2\v.go.OptionsR\x05oneof:>\n" +
	"\x04enum\x12\x1c.google.protobuf.EnumOptions\x18\xda6 \x01(\v2\v.go.OptionsR\x04enum:E\n" +
	"\x05value\x12!.google.protobuf.EnumValueOptions\x18\xda6 \x01(\v2\v.go.OptionsR\x05value:B\n" +
	"\x04file\x12\x1c.google.protobuf.FileOptions\x18\xda6 \x01(\v2\x0f.go.FileOptionsR\x04fileBH\n" +
	"\x1exyz.hoper.protobuf.utils.patchZ&github.com/hopeio/protobuf/utils/patch"

var (
	file_hopeio_utils_patch_go_proto_rawDescOnce sync.Once
	file_hopeio_utils_patch_go_proto_rawDescData []byte
)

func file_hopeio_utils_patch_go_proto_rawDescGZIP() []byte {
	file_hopeio_utils_patch_go_proto_rawDescOnce.Do(func() {
		file_hopeio_utils_patch_go_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_hopeio_utils_patch_go_proto_rawDesc), len(file_hopeio_utils_patch_go_proto_rawDesc)))
	})
	return file_hopeio_utils_patch_go_proto_rawDescData
}

var file_hopeio_utils_patch_go_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_hopeio_utils_patch_go_proto_goTypes = []any{
	(*Options)(nil),                       // 0: go.Options
	(*FileOptions)(nil),                   // 1: go.FileOptions
	(*descriptorpb.MessageOptions)(nil),   // 2: google.protobuf.MessageOptions
	(*descriptorpb.FieldOptions)(nil),     // 3: google.protobuf.FieldOptions
	(*descriptorpb.OneofOptions)(nil),     // 4: google.protobuf.OneofOptions
	(*descriptorpb.EnumOptions)(nil),      // 5: google.protobuf.EnumOptions
	(*descriptorpb.EnumValueOptions)(nil), // 6: google.protobuf.EnumValueOptions
	(*descriptorpb.FileOptions)(nil),      // 7: google.protobuf.FileOptions
}
var file_hopeio_utils_patch_go_proto_depIdxs = []int32{
	2,  // 0: go.message:extendee -> google.protobuf.MessageOptions
	3,  // 1: go.field:extendee -> google.protobuf.FieldOptions
	4,  // 2: go.oneof:extendee -> google.protobuf.OneofOptions
	5,  // 3: go.enum:extendee -> google.protobuf.EnumOptions
	6,  // 4: go.value:extendee -> google.protobuf.EnumValueOptions
	7,  // 5: go.file:extendee -> google.protobuf.FileOptions
	0,  // 6: go.message:type_name -> go.Options
	0,  // 7: go.field:type_name -> go.Options
	0,  // 8: go.oneof:type_name -> go.Options
	0,  // 9: go.enum:type_name -> go.Options
	0,  // 10: go.value:type_name -> go.Options
	1,  // 11: go.file:type_name -> go.FileOptions
	12, // [12:12] is the sub-list for method output_type
	12, // [12:12] is the sub-list for method input_type
	6,  // [6:12] is the sub-list for extension type_name
	0,  // [0:6] is the sub-list for extension extendee
	0,  // [0:0] is the sub-list for field type_name
}

func init() { file_hopeio_utils_patch_go_proto_init() }
func file_hopeio_utils_patch_go_proto_init() {
	if File_hopeio_utils_patch_go_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_hopeio_utils_patch_go_proto_rawDesc), len(file_hopeio_utils_patch_go_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 6,
			NumServices:   0,
		},
		GoTypes:           file_hopeio_utils_patch_go_proto_goTypes,
		DependencyIndexes: file_hopeio_utils_patch_go_proto_depIdxs,
		MessageInfos:      file_hopeio_utils_patch_go_proto_msgTypes,
		ExtensionInfos:    file_hopeio_utils_patch_go_proto_extTypes,
	}.Build()
	File_hopeio_utils_patch_go_proto = out.File
	file_hopeio_utils_patch_go_proto_goTypes = nil
	file_hopeio_utils_patch_go_proto_depIdxs = nil
}
