//
// Copyright 2024 hopeio. All rights reserved.
// Licensed under the MIT License that can be found in the LICENSE file.
// @Created by jyb

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        v6.32.0
// source: hopeio/model/dict/dict.proto

package dict

import (
	_ "github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-openapiv2/options"
	deletedAt "github.com/hopeio/protobuf/time/deletedAt"
	timestamp "github.com/hopeio/protobuf/time/timestamp"
	_ "github.com/hopeio/protobuf/utils/patch"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Dict struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty" gorm:"primaryKey"`
	Group         uint32                 `protobuf:"varint,2,opt,name=group,proto3" json:"group,omitempty"`
	Key           string                 `protobuf:"bytes,4,opt,name=key,proto3" json:"key,omitempty" gorm:"键"`
	Value         string                 `protobuf:"bytes,5,opt,name=value,proto3" json:"value,omitempty" comment:"值"`
	Type          uint32                 `protobuf:"varint,6,opt,name=type,proto3" json:"type,omitempty" comment:"类型"`
	Seq           uint32                 `protobuf:"varint,7,opt,name=seq,proto3" json:"seq,omitempty" comment:"顺序"`
	CreatedAt     *timestamp.Timestamp   `protobuf:"bytes,16,opt,name=createdAt,proto3" json:"createdAt,omitempty" gorm:"type:timestamptz(6);default:now();index"`
	UpdatedAt     *timestamp.Timestamp   `protobuf:"bytes,26,opt,name=updatedAt,proto3" json:"updatedAt,omitempty" gorm:"type:timestamptz(6)"`
	DeletedAt     *deletedAt.DeletedAt   `protobuf:"bytes,28,opt,name=deletedAt,proto3" json:"deletedAt,omitempty" gorm:"<-:false;type:timestamptz(6);index"`
	Status        uint32                 `protobuf:"varint,18,opt,name=status,proto3" json:"status,omitempty" gorm:"type:int2;default:0"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Dict) Reset() {
	*x = Dict{}
	mi := &file_hopeio_model_dict_dict_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Dict) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Dict) ProtoMessage() {}

func (x *Dict) ProtoReflect() protoreflect.Message {
	mi := &file_hopeio_model_dict_dict_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Dict.ProtoReflect.Descriptor instead.
func (*Dict) Descriptor() ([]byte, []int) {
	return file_hopeio_model_dict_dict_proto_rawDescGZIP(), []int{0}
}

func (x *Dict) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Dict) GetGroup() uint32 {
	if x != nil {
		return x.Group
	}
	return 0
}

func (x *Dict) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *Dict) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *Dict) GetType() uint32 {
	if x != nil {
		return x.Type
	}
	return 0
}

func (x *Dict) GetSeq() uint32 {
	if x != nil {
		return x.Seq
	}
	return 0
}

func (x *Dict) GetCreatedAt() *timestamp.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Dict) GetUpdatedAt() *timestamp.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *Dict) GetDeletedAt() *deletedAt.DeletedAt {
	if x != nil {
		return x.DeletedAt
	}
	return nil
}

func (x *Dict) GetStatus() uint32 {
	if x != nil {
		return x.Status
	}
	return 0
}

var File_hopeio_model_dict_dict_proto protoreflect.FileDescriptor

const file_hopeio_model_dict_dict_proto_rawDesc = "" +
	"\n" +
	"\x1chopeio/model/dict/dict.proto\x12\x04dict\x1a\x1bhopeio/utils/patch/go.proto\x1a%hopeio/time/timestamp/timestamp.proto\x1a%hopeio/time/deletedAt/deletedAt.proto\x1a.protoc-gen-openapiv2/options/annotations.proto\"\xec\x04\n" +
	"\x04Dict\x12(\n" +
	"\x02id\x18\x01 \x01(\x04B\x18ҵ\x03\x14\xa2\x01\x11gorm:\"primaryKey\"R\x02id\x12)\n" +
	"\x05group\x18\x02 \x01(\rB\x13ҵ\x03\x0f\xa2\x01\fcomment:\"组R\x05group\x12#\n" +
	"\x03key\x18\x04 \x01(\tB\x11ҵ\x03\r\xa2\x01\n" +
	"gorm:\"键\"R\x03key\x12*\n" +
	"\x05value\x18\x05 \x01(\tB\x14ҵ\x03\x10\xa2\x01\rcomment:\"值\"R\x05value\x12+\n" +
	"\x04type\x18\x06 \x01(\rB\x17ҵ\x03\x13\xa2\x01\x10comment:\"类型\"R\x04type\x12)\n" +
	"\x03seq\x18\a \x01(\rB\x17ҵ\x03\x13\xa2\x01\x10comment:\"顺序\"R\x03seq\x12i\n" +
	"\tcreatedAt\x18\x10 \x01(\v2\x14.timestamp.TimestampB5ҵ\x031\xa2\x01.gorm:\"type:timestamptz(6);default:now();index\"R\tcreatedAt\x12U\n" +
	"\tupdatedAt\x18\x1a \x01(\v2\x14.timestamp.TimestampB!ҵ\x03\x1d\xa2\x01\x1agorm:\"type:timestamptz(6)\"R\tupdatedAt\x12d\n" +
	"\tdeletedAt\x18\x1c \x01(\v2\x14.deletedAt.DeletedAtB0ҵ\x03,\xa2\x01)gorm:\"<-:false;type:timestamptz(6);index\"R\tdeletedAt\x12>\n" +
	"\x06status\x18\x12 \x01(\rB&\x92A\x02@\x01ҵ\x03\x1d\xa2\x01\x1agorm:\"type:int2;default:0\"R\x06statusBH\n" +
	"\x1dxyz.hoper.protobuf.model.dictP\x01Z%github.com/hopeio/protobuf/model/dictb\x06proto3"

var (
	file_hopeio_model_dict_dict_proto_rawDescOnce sync.Once
	file_hopeio_model_dict_dict_proto_rawDescData []byte
)

func file_hopeio_model_dict_dict_proto_rawDescGZIP() []byte {
	file_hopeio_model_dict_dict_proto_rawDescOnce.Do(func() {
		file_hopeio_model_dict_dict_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_hopeio_model_dict_dict_proto_rawDesc), len(file_hopeio_model_dict_dict_proto_rawDesc)))
	})
	return file_hopeio_model_dict_dict_proto_rawDescData
}

var file_hopeio_model_dict_dict_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_hopeio_model_dict_dict_proto_goTypes = []any{
	(*Dict)(nil),                // 0: dict.Dict
	(*timestamp.Timestamp)(nil), // 1: timestamp.Timestamp
	(*deletedAt.DeletedAt)(nil), // 2: deletedAt.DeletedAt
}
var file_hopeio_model_dict_dict_proto_depIdxs = []int32{
	1, // 0: dict.Dict.createdAt:type_name -> timestamp.Timestamp
	1, // 1: dict.Dict.updatedAt:type_name -> timestamp.Timestamp
	2, // 2: dict.Dict.deletedAt:type_name -> deletedAt.DeletedAt
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_hopeio_model_dict_dict_proto_init() }
func file_hopeio_model_dict_dict_proto_init() {
	if File_hopeio_model_dict_dict_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_hopeio_model_dict_dict_proto_rawDesc), len(file_hopeio_model_dict_dict_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_hopeio_model_dict_dict_proto_goTypes,
		DependencyIndexes: file_hopeio_model_dict_dict_proto_depIdxs,
		MessageInfos:      file_hopeio_model_dict_dict_proto_msgTypes,
	}.Build()
	File_hopeio_model_dict_dict_proto = out.File
	file_hopeio_model_dict_dict_proto_goTypes = nil
	file_hopeio_model_dict_dict_proto_depIdxs = nil
}
