//
// Copyright 2024 hopeio. All rights reserved.
// Licensed under the MIT License that can be found in the LICENSE file.
// @Created by jyb

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.32.0
// source: hopeio/time/time.proto

package time

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Date struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Days          int32                  `protobuf:"varint,1,opt,name=days,proto3" json:"days,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Date) Reset() {
	*x = Date{}
	mi := &file_hopeio_time_time_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Date) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Date) ProtoMessage() {}

func (x *Date) ProtoReflect() protoreflect.Message {
	mi := &file_hopeio_time_time_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Date.ProtoReflect.Descriptor instead.
func (*Date) Descriptor() ([]byte, []int) {
	return file_hopeio_time_time_proto_rawDescGZIP(), []int{0}
}

func (x *Date) GetDays() int32 {
	if x != nil {
		return x.Days
	}
	return 0
}

type Duration struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Micro         int64                  `protobuf:"varint,1,opt,name=micro,proto3" json:"micro,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Duration) Reset() {
	*x = Duration{}
	mi := &file_hopeio_time_time_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Duration) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Duration) ProtoMessage() {}

func (x *Duration) ProtoReflect() protoreflect.Message {
	mi := &file_hopeio_time_time_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Duration.ProtoReflect.Descriptor instead.
func (*Duration) Descriptor() ([]byte, []int) {
	return file_hopeio_time_time_proto_rawDescGZIP(), []int{1}
}

func (x *Duration) GetMicro() int64 {
	if x != nil {
		return x.Micro
	}
	return 0
}

type Timestamp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Millis        int64                  `protobuf:"varint,1,opt,name=millis,proto3" json:"millis,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Timestamp) Reset() {
	*x = Timestamp{}
	mi := &file_hopeio_time_time_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Timestamp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Timestamp) ProtoMessage() {}

func (x *Timestamp) ProtoReflect() protoreflect.Message {
	mi := &file_hopeio_time_time_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Timestamp.ProtoReflect.Descriptor instead.
func (*Timestamp) Descriptor() ([]byte, []int) {
	return file_hopeio_time_time_proto_rawDescGZIP(), []int{2}
}

func (x *Timestamp) GetMillis() int64 {
	if x != nil {
		return x.Millis
	}
	return 0
}

var File_hopeio_time_time_proto protoreflect.FileDescriptor

const file_hopeio_time_time_proto_rawDesc = "" +
	"\n" +
	"\x16hopeio/time/time.proto\x12\x04time\"\x1a\n" +
	"\x04Date\x12\x12\n" +
	"\x04days\x18\x01 \x01(\x05R\x04days\" \n" +
	"\bDuration\x12\x14\n" +
	"\x05micro\x18\x01 \x01(\x03R\x05micro\"#\n" +
	"\tTimestamp\x12\x16\n" +
	"\x06millis\x18\x01 \x01(\x03R\x06millisB<\n" +
	"\x17xyz.hoper.protobuf.timeP\x01Z\x1fgithub.com/hopeio/protobuf/timeb\x06proto3"

var (
	file_hopeio_time_time_proto_rawDescOnce sync.Once
	file_hopeio_time_time_proto_rawDescData []byte
)

func file_hopeio_time_time_proto_rawDescGZIP() []byte {
	file_hopeio_time_time_proto_rawDescOnce.Do(func() {
		file_hopeio_time_time_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_hopeio_time_time_proto_rawDesc), len(file_hopeio_time_time_proto_rawDesc)))
	})
	return file_hopeio_time_time_proto_rawDescData
}

var file_hopeio_time_time_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_hopeio_time_time_proto_goTypes = []any{
	(*Date)(nil),      // 0: time.Date
	(*Duration)(nil),  // 1: time.Duration
	(*Timestamp)(nil), // 2: time.Timestamp
}
var file_hopeio_time_time_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_hopeio_time_time_proto_init() }
func file_hopeio_time_time_proto_init() {
	if File_hopeio_time_time_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_hopeio_time_time_proto_rawDesc), len(file_hopeio_time_time_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_hopeio_time_time_proto_goTypes,
		DependencyIndexes: file_hopeio_time_time_proto_depIdxs,
		MessageInfos:      file_hopeio_time_time_proto_msgTypes,
	}.Build()
	File_hopeio_time_time_proto = out.File
	file_hopeio_time_time_proto_goTypes = nil
	file_hopeio_time_time_proto_depIdxs = nil
}
