// Code generated by protoc-gen-grpc-gin. DO NOT EDIT.
// source: stream.proto

/*
Package stream_test is a reverse proxy.

It translates gRPC into RESTful JSON APIs.
*/
package stream_test

import (
	"io"
	"strconv"

	"github.com/gin-gonic/gin"
	"github.com/hopeio/gox"
	grpc_0 "github.com/hopeio/gox/net/http/grpc"
	"github.com/hopeio/gox/strings"
	"github.com/hopeio/protobuf/tools/protoc-gen-grpc-gin/gateway"
	"google.golang.org/grpc"
	"google.golang.org/grpc/codes"
	"google.golang.org/grpc/metadata"
	"google.golang.org/grpc/status"
	"google.golang.org/protobuf/proto"
)

// Suppress "imported and not used" errors
var _ codes.Code
var _ io.Reader
var _ status.Status
var _ = metadata.Join
var _ = gox.Pointer[bool]
var _ = strings.Bool
var _ = strconv.Itoa

func local_request_DemoService_Ping_0(server DemoServiceServer, ctx *gin.Context) (proto.Message, grpc_0.ServerMetadata, error) {
	var stream grpc_0.ServerTransportStream
	var protoReq PingRequest

	if err := gateway.Bind(ctx, &protoReq); err != nil {
		return nil, stream.ServerMetadata(), err
	}

	ctx.Request = ctx.Request.WithContext(grpc.NewContextWithServerTransportStream(metadata.NewIncomingContext(ctx.Request.Context(), metadata.MD(ctx.Request.Header)), &stream))

	resp, err := server.Ping(ctx.Request.Context(), &protoReq)
	return resp, stream.ServerMetadata(), err

}

func local_request_DemoService_Search_0(server DemoServiceServer, ctx *gin.Context) {
	var protoReq SearchRequest
	var err error

	if err = gateway.Bind(ctx, &protoReq); err != nil {
		gateway.HttpError(ctx, err)
		return
	}

	ctx.Request = ctx.Request.WithContext(grpc.NewContextWithServerTransportStream(metadata.NewIncomingContext(ctx.Request.Context(), metadata.MD(ctx.Request.Header)), &grpc_0.ServerTransportStream{}))

	stream := gateway.NewServerStream[*SearchResult](ctx)
	defer func() {
		if stream.Status() {
			if err != nil {
				s := status.Code(err)
				ctx.Writer.Header().Set("Grpc-Status", strconv.Itoa(int(s)))
				ctx.Writer.Header().Set("Grpc-Message", err.Error())
			} else {
				ctx.Writer.Header().Set("Grpc-Status", "0")
			}
		}
	}()
	if err = server.Search(&protoReq, stream); err != nil {
		gateway.HttpError(ctx, err)
		return
	}
}

// RegisterDemoServiceHandlerServer registers the http handlers for service DemoService to "mux".
// UnaryRPC        : call DemoServiceServer directly.
// ServerStreaming : HTTP/2 chunked with gRPC length-prefixed JSON frames.
// ClientStreaming : currently unsupported.
func RegisterDemoServiceHandlerServer(mux *gin.Engine, server DemoServiceServer) {

	mux.Handle("GET", "/api/v1/ping", func(ctx *gin.Context) {
		resp, md, err := local_request_DemoService_Ping_0(server, ctx)
		if err != nil {
			gateway.HttpError(ctx, err)
			return
		}

		gateway.ForwardResponseMessage(ctx, md, resp)

	})

	mux.Handle("GET", "/api/v1/search", func(ctx *gin.Context) {
		local_request_DemoService_Search_0(server, ctx)
	})

	mux.Handle("POST", "/api/v1/upload", func(ctx *gin.Context) {
		err := status.Error(codes.Unimplemented, "client streaming is not yet supported")
		gateway.HttpError(ctx, err)
		return
	})

	mux.Handle("POST", "/api/v1/chat", func(ctx *gin.Context) {
		err := status.Error(codes.Unimplemented, "bidirectional streaming is not yet supported")
		gateway.HttpError(ctx, err)
		return
	})

}
