//
// Copyright 2024 hopeio. All rights reserved.
// Licensed under the MIT License that can be found in the LICENSE file.
// @Created by jyb

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.1
// source: hopeio/oauth/oauth.proto

package oauth

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type OauthReq struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ResponseType   string                 `protobuf:"bytes,1,opt,name=responseType,proto3" json:"responseType,omitempty"`
	ClientID       string                 `protobuf:"bytes,2,opt,name=clientID,proto3" json:"clientID,omitempty"`
	Scope          string                 `protobuf:"bytes,3,opt,name=scope,proto3" json:"scope,omitempty"`
	RedirectURI    string                 `protobuf:"bytes,4,opt,name=redirectURI,proto3" json:"redirectURI,omitempty"`
	State          string                 `protobuf:"bytes,5,opt,name=state,proto3" json:"state,omitempty"`
	UserID         string                 `protobuf:"bytes,6,opt,name=userID,proto3" json:"userID,omitempty"`
	AccessTokenExp int64                  `protobuf:"varint,7,opt,name=accessTokenExp,proto3" json:"accessTokenExp,omitempty"`
	ClientSecret   string                 `protobuf:"bytes,11,opt,name=clientSecret,proto3" json:"clientSecret,omitempty"`
	Code           string                 `protobuf:"bytes,12,opt,name=code,proto3" json:"code,omitempty"`
	RefreshToken   string                 `protobuf:"bytes,13,opt,name=refreshToken,proto3" json:"refreshToken,omitempty"`
	GrantType      string                 `protobuf:"bytes,14,opt,name=grantType,proto3" json:"grantType,omitempty"`
	AccessType     string                 `protobuf:"bytes,15,opt,name=accessType,proto3" json:"accessType,omitempty"`
	LoginURI       string                 `protobuf:"bytes,16,opt,name=loginURI,proto3" json:"loginURI,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *OauthReq) Reset() {
	*x = OauthReq{}
	mi := &file_hopeio_oauth_oauth_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OauthReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OauthReq) ProtoMessage() {}

func (x *OauthReq) ProtoReflect() protoreflect.Message {
	mi := &file_hopeio_oauth_oauth_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OauthReq.ProtoReflect.Descriptor instead.
func (*OauthReq) Descriptor() ([]byte, []int) {
	return file_hopeio_oauth_oauth_proto_rawDescGZIP(), []int{0}
}

func (x *OauthReq) GetResponseType() string {
	if x != nil {
		return x.ResponseType
	}
	return ""
}

func (x *OauthReq) GetClientID() string {
	if x != nil {
		return x.ClientID
	}
	return ""
}

func (x *OauthReq) GetScope() string {
	if x != nil {
		return x.Scope
	}
	return ""
}

func (x *OauthReq) GetRedirectURI() string {
	if x != nil {
		return x.RedirectURI
	}
	return ""
}

func (x *OauthReq) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *OauthReq) GetUserID() string {
	if x != nil {
		return x.UserID
	}
	return ""
}

func (x *OauthReq) GetAccessTokenExp() int64 {
	if x != nil {
		return x.AccessTokenExp
	}
	return 0
}

func (x *OauthReq) GetClientSecret() string {
	if x != nil {
		return x.ClientSecret
	}
	return ""
}

func (x *OauthReq) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *OauthReq) GetRefreshToken() string {
	if x != nil {
		return x.RefreshToken
	}
	return ""
}

func (x *OauthReq) GetGrantType() string {
	if x != nil {
		return x.GrantType
	}
	return ""
}

func (x *OauthReq) GetAccessType() string {
	if x != nil {
		return x.AccessType
	}
	return ""
}

func (x *OauthReq) GetLoginURI() string {
	if x != nil {
		return x.LoginURI
	}
	return ""
}

type Client struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ID            string                 `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Secret        string                 `protobuf:"bytes,2,opt,name=secret,proto3" json:"secret,omitempty"`
	Domain        string                 `protobuf:"bytes,3,opt,name=domain,proto3" json:"domain,omitempty"`
	UserID        string                 `protobuf:"bytes,4,opt,name=userID,proto3" json:"userID,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Client) Reset() {
	*x = Client{}
	mi := &file_hopeio_oauth_oauth_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Client) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Client) ProtoMessage() {}

func (x *Client) ProtoReflect() protoreflect.Message {
	mi := &file_hopeio_oauth_oauth_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Client.ProtoReflect.Descriptor instead.
func (*Client) Descriptor() ([]byte, []int) {
	return file_hopeio_oauth_oauth_proto_rawDescGZIP(), []int{1}
}

func (x *Client) GetID() string {
	if x != nil {
		return x.ID
	}
	return ""
}

func (x *Client) GetSecret() string {
	if x != nil {
		return x.Secret
	}
	return ""
}

func (x *Client) GetDomain() string {
	if x != nil {
		return x.Domain
	}
	return ""
}

func (x *Client) GetUserID() string {
	if x != nil {
		return x.UserID
	}
	return ""
}

var File_hopeio_oauth_oauth_proto protoreflect.FileDescriptor

const file_hopeio_oauth_oauth_proto_rawDesc = "" +
	"\n" +
	"\x18hopeio/oauth/oauth.proto\x12\x05oauth\"\x8e\x03\n" +
	"\bOauthReq\x12\"\n" +
	"\fresponseType\x18\x01 \x01(\tR\fresponseType\x12\x1a\n" +
	"\bclientID\x18\x02 \x01(\tR\bclientID\x12\x14\n" +
	"\x05scope\x18\x03 \x01(\tR\x05scope\x12 \n" +
	"\vredirectURI\x18\x04 \x01(\tR\vredirectURI\x12\x14\n" +
	"\x05state\x18\x05 \x01(\tR\x05state\x12\x16\n" +
	"\x06userID\x18\x06 \x01(\tR\x06userID\x12&\n" +
	"\x0eaccessTokenExp\x18\a \x01(\x03R\x0eaccessTokenExp\x12\"\n" +
	"\fclientSecret\x18\v \x01(\tR\fclientSecret\x12\x12\n" +
	"\x04code\x18\f \x01(\tR\x04code\x12\"\n" +
	"\frefreshToken\x18\r \x01(\tR\frefreshToken\x12\x1c\n" +
	"\tgrantType\x18\x0e \x01(\tR\tgrantType\x12\x1e\n" +
	"\n" +
	"accessType\x18\x0f \x01(\tR\n" +
	"accessType\x12\x1a\n" +
	"\bloginURI\x18\x10 \x01(\tR\bloginURI\"`\n" +
	"\x06Client\x12\x0e\n" +
	"\x02ID\x18\x01 \x01(\tR\x02ID\x12\x16\n" +
	"\x06secret\x18\x02 \x01(\tR\x06secret\x12\x16\n" +
	"\x06domain\x18\x03 \x01(\tR\x06domain\x12\x16\n" +
	"\x06userID\x18\x04 \x01(\tR\x06userIDB>\n" +
	"\x18xyz.hoper.protobuf.oauthP\x01Z github.com/hopeio/protobuf/oauthb\x06proto3"

var (
	file_hopeio_oauth_oauth_proto_rawDescOnce sync.Once
	file_hopeio_oauth_oauth_proto_rawDescData []byte
)

func file_hopeio_oauth_oauth_proto_rawDescGZIP() []byte {
	file_hopeio_oauth_oauth_proto_rawDescOnce.Do(func() {
		file_hopeio_oauth_oauth_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_hopeio_oauth_oauth_proto_rawDesc), len(file_hopeio_oauth_oauth_proto_rawDesc)))
	})
	return file_hopeio_oauth_oauth_proto_rawDescData
}

var file_hopeio_oauth_oauth_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_hopeio_oauth_oauth_proto_goTypes = []any{
	(*OauthReq)(nil), // 0: oauth.OauthReq
	(*Client)(nil),   // 1: oauth.Client
}
var file_hopeio_oauth_oauth_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_hopeio_oauth_oauth_proto_init() }
func file_hopeio_oauth_oauth_proto_init() {
	if File_hopeio_oauth_oauth_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_hopeio_oauth_oauth_proto_rawDesc), len(file_hopeio_oauth_oauth_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_hopeio_oauth_oauth_proto_goTypes,
		DependencyIndexes: file_hopeio_oauth_oauth_proto_depIdxs,
		MessageInfos:      file_hopeio_oauth_oauth_proto_msgTypes,
	}.Build()
	File_hopeio_oauth_oauth_proto = out.File
	file_hopeio_oauth_oauth_proto_goTypes = nil
	file_hopeio_oauth_oauth_proto_depIdxs = nil
}
