//
// Copyright 2024 hopeio. All rights reserved.
// Licensed under the MIT License that can be found in the LICENSE file.
// @Created by jyb

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.1
// source: hopeio/time/deletedAt/deletedAt.proto

package deletedAt

import (
	_ "github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-openapiv2/options"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DeletedAt struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Represents seconds of UTC time since Unix epoch
	// 1970-01-01T00:00:00Z. Must be from 0001-01-01T00:00:00Z to
	// 9999-12-31T23:59:59Z inclusive.
	Seconds int64 `protobuf:"varint,1,opt,name=seconds,proto3" json:"seconds,omitempty"`
	// Non-negative fractions of a second at nanosecond resolution. Negative
	// second values with fractions must still have non-negative nanos values
	// that count forward in time. Must be from 0 to 999,999,999
	// inclusive.
	Nanos         int32 `protobuf:"varint,2,opt,name=nanos,proto3" json:"nanos,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeletedAt) Reset() {
	*x = DeletedAt{}
	mi := &file_hopeio_time_deletedAt_deletedAt_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeletedAt) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeletedAt) ProtoMessage() {}

func (x *DeletedAt) ProtoReflect() protoreflect.Message {
	mi := &file_hopeio_time_deletedAt_deletedAt_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeletedAt.ProtoReflect.Descriptor instead.
func (*DeletedAt) Descriptor() ([]byte, []int) {
	return file_hopeio_time_deletedAt_deletedAt_proto_rawDescGZIP(), []int{0}
}

func (x *DeletedAt) GetSeconds() int64 {
	if x != nil {
		return x.Seconds
	}
	return 0
}

func (x *DeletedAt) GetNanos() int32 {
	if x != nil {
		return x.Nanos
	}
	return 0
}

type DeletedAtTimestamp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Mills         int64                  `protobuf:"varint,1,opt,name=mills,proto3" json:"mills,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeletedAtTimestamp) Reset() {
	*x = DeletedAtTimestamp{}
	mi := &file_hopeio_time_deletedAt_deletedAt_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeletedAtTimestamp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeletedAtTimestamp) ProtoMessage() {}

func (x *DeletedAtTimestamp) ProtoReflect() protoreflect.Message {
	mi := &file_hopeio_time_deletedAt_deletedAt_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeletedAtTimestamp.ProtoReflect.Descriptor instead.
func (*DeletedAtTimestamp) Descriptor() ([]byte, []int) {
	return file_hopeio_time_deletedAt_deletedAt_proto_rawDescGZIP(), []int{1}
}

func (x *DeletedAtTimestamp) GetMills() int64 {
	if x != nil {
		return x.Mills
	}
	return 0
}

var File_hopeio_time_deletedAt_deletedAt_proto protoreflect.FileDescriptor

const file_hopeio_time_deletedAt_deletedAt_proto_rawDesc = "" +
	"\n" +
	"%hopeio/time/deletedAt/deletedAt.proto\x12\tdeletedAt\x1a.protoc-gen-openapiv2/options/annotations.proto\"g\n" +
	"\tDeletedAt\x12\x18\n" +
	"\aseconds\x18\x01 \x01(\x03R\aseconds\x12\x14\n" +
	"\x05nanos\x18\x02 \x01(\x05R\x05nanos:*\x92A'2%\"2006-01-02T15:04:05.999999999Z07:00\"\"*\n" +
	"\x12DeletedAtTimestamp\x12\x14\n" +
	"\x05mills\x18\x01 \x01(\x03R\x05millsBK\n" +
	"\x1cxyz.hoper.protobuf.deletedAtP\x01Z)github.com/hopeio/protobuf/time/deletedAtb\x06proto3"

var (
	file_hopeio_time_deletedAt_deletedAt_proto_rawDescOnce sync.Once
	file_hopeio_time_deletedAt_deletedAt_proto_rawDescData []byte
)

func file_hopeio_time_deletedAt_deletedAt_proto_rawDescGZIP() []byte {
	file_hopeio_time_deletedAt_deletedAt_proto_rawDescOnce.Do(func() {
		file_hopeio_time_deletedAt_deletedAt_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_hopeio_time_deletedAt_deletedAt_proto_rawDesc), len(file_hopeio_time_deletedAt_deletedAt_proto_rawDesc)))
	})
	return file_hopeio_time_deletedAt_deletedAt_proto_rawDescData
}

var file_hopeio_time_deletedAt_deletedAt_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_hopeio_time_deletedAt_deletedAt_proto_goTypes = []any{
	(*DeletedAt)(nil),          // 0: deletedAt.DeletedAt
	(*DeletedAtTimestamp)(nil), // 1: deletedAt.DeletedAtTimestamp
}
var file_hopeio_time_deletedAt_deletedAt_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_hopeio_time_deletedAt_deletedAt_proto_init() }
func file_hopeio_time_deletedAt_deletedAt_proto_init() {
	if File_hopeio_time_deletedAt_deletedAt_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_hopeio_time_deletedAt_deletedAt_proto_rawDesc), len(file_hopeio_time_deletedAt_deletedAt_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_hopeio_time_deletedAt_deletedAt_proto_goTypes,
		DependencyIndexes: file_hopeio_time_deletedAt_deletedAt_proto_depIdxs,
		MessageInfos:      file_hopeio_time_deletedAt_deletedAt_proto_msgTypes,
	}.Build()
	File_hopeio_time_deletedAt_deletedAt_proto = out.File
	file_hopeio_time_deletedAt_deletedAt_proto_goTypes = nil
	file_hopeio_time_deletedAt_deletedAt_proto_depIdxs = nil
}
